local dailyTasksData = {
	{
		name = "Undeads",
		items = {
			{ id = 9649, count = 5 },
			{ id = 10291, count = 8 },
			{ id = 10283, count = 3 },
		},
		requiredKills = 120,
		creatures = {
			"ghoul",
			"mummy",
			"skeleton",
			"skeleton warrior",
			"crypt shambler",
			"zombie",
		},
		exp = 8000,
		money = 3000,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Apes",
		items = { { id = 11511, count = 5 }, { id = 11471, count = 2 } },
		requiredKills = 100,
		creatures = { "kongra", "merlkin", "sibang" },
		exp = 10000,
		money = 3500,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Orcs",
		items = { { id = 11480, count = 3 }, { id = 11453, count = 10 } },
		requiredKills = 130,
		creatures = {
			"orc",
			"orc berserker",
			"orc leader",
			"orc rider",
			"orc shaman",
			"orc spearman",
			"orc warlord",
			"orc warrior",
		},
		exp = 13000,
		money = 3000,
		tibiaCoins = 1,
		min = 0,
		max = 90,
	},
	{
		name = "Crocodiles",
		items = { { id = 10279, count = 20 } },
		requiredKills = 100,
		creatures = { "crocodile" },
		exp = 8000,
		money = 2500,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Cyclops",
		items = { { id = 9657, count = 12 } },
		requiredKills = 60,
		creatures = { "cyclops", "cyclops drone", "cyclops smith" },
		exp = 13000,
		money = 4000,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Gargoyles",
		items = { { id = 10278, count = 6 } },
		requiredKills = 80,
		creatures = { "gargoyle" },
		exp = 15000,
		money = 4000,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Trolls",
		items = { { id = 9689, count = 2 } },
		requiredKills = 70,
		creatures = { "troll", "troll champion", "swamp troll" },
		exp = 5000,
		money = 1500,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Minotaurs",
		items = { { id = 11472, count = 5 }, { id = 11451, count = 5 } },
		requiredKills = 150,
		creatures = {
			"minotaur",
			"minotaur mage",
			"minotaur archer",
			"minotaur guard",
		},
		exp = 15000,
		money = 5000,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Rotworms",
		items = { { id = 9692, count = 5 }, { id = 10275, count = 3 } },
		requiredKills = 100,
		creatures = { "rotworm", "carrion worm" },
		exp = 5000,
		money = 2000,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Stone Golems",
		items = { { id = 10315, count = 2 } },
		requiredKills = 50,
		creatures = { "stone golem" },
		exp = 10000,
		money = 3000,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Tarantulas",
		items = { { id = 10281, count = 10 } },
		requiredKills = 100,
		creatures = { "tarantula" },
		exp = 10000,
		money = 5000,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Tortoises",
		items = { { id = 5678, count = 3 } },
		requiredKills = 80,
		creatures = { "tortoise", "thornback tortoise" },
		exp = 10000,
		money = 4000,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Scarabs",
		items = { { id = 9641, count = 4 } },
		requiredKills = 80,
		creatures = { "scarab" },
		exp = 11000,
		money = 3500,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Goblins",
		items = { { id = 11539, count = 1 } },
		requiredKills = 100,
		creatures = { "goblin", "goblin assassin", "goblin scavenger" },
		exp = 7000,
		money = 3500,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Amazons",
		items = { { id = 11443, count = 10 } },
		requiredKills = 100,
		creatures = { "amazon", "valkyrie" },
		exp = 15000,
		money = 2000,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Elves",
		items = { { id = 9635, count = 5 } },
		requiredKills = 150,
		creatures = { "elf", "elf scout", "elf arcanist" },
		exp = 15000,
		money = 5000,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Hunters",
		items = { { id = 11469, count = 4 } },
		requiredKills = 100,
		creatures = { "hunter", "poacher" },
		exp = 18000,
		money = 4000,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Dwarves",
		items = { { id = 3375, count = 1 } },
		requiredKills = 150,
		creatures = {
			"dwarf",
			"dwarf miner",
			"dwarf geomancer",
			"dwarf soldier",
			"dwarf guard",
		},
		exp = 14000,
		money = 3500,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	},
	{
		name = "Mutated Humans",
		items = { { id = 10308, count = 5 } },
		requiredKills = 100,
		creatures = { "mutated human" },
		exp = 15000,
		money = 3500,
		tibiaCoins = 1,
		min = 0,
		max = 69,
	}, -- 50+ lvl
	{
		name = "Green Dragons",
		items = { { id = 11457, count = 5 } },
		requiredKills = 50,
		creatures = { "dragon", "dragon hatchling" },
		exp = 36000,
		money = 5000,
		tibiaCoins = 2,
		min = 30,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Insects",
		items = {
			{ id = 14083, count = 8 },
			{ id = 14081, count = 6 },
			{ id = 14078, count = 5 },
		},
		requiredKills = 150,
		creatures = {
			"swarmer",
			"spitter",
			"crawler",
			"hive overseer",
			"insectoid worker",
			"kollos",
			"spidris",
			"spidris elite",
			"waspoid",
		},
		exp = 65000,
		money = 5000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Coryms",
		items = {
			{ id = 17809, count = 8 },
			{ id = 17819, count = 8 },
			{ id = 17817, count = 8 },
		},
		requiredKills = 120,
		creatures = { "corym charlatan", "corym skirmisher", "corym vanguard" },
		exp = 35000,
		money = 4000,
		tibiaCoins = 2,
		min = 30,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Ancient Scarabs",
		items = { { id = 9631, count = 5 } },
		requiredKills = 60,
		creatures = { "ancient scarab" },
		exp = 40000,
		money = 5000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Bonebeasts",
		items = { { id = 10277, count = 5 } },
		requiredKills = 60,
		creatures = { "bonebeast" },
		exp = 35000,
		money = 8000,
		tibiaCoins = 2,
		min = 30,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Crystal Spiders",
		items = { { id = 7449, count = 1 } },
		requiredKills = 60,
		creatures = { "crystal spider" },
		exp = 55000,
		money = 5000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Wailing Widows",
		items = { { id = 10411, count = 7 } },
		requiredKills = 70,
		creatures = { "wailing widow" },
		exp = 40000,
		money = 7000,
		tibiaCoins = 3,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Mutated Tigers",
		items = { { id = 10293, count = 10 } },
		requiredKills = 80,
		creatures = { "mutated tiger" },
		exp = 40000,
		money = 5000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Necromancers",
		items = { { id = 10320, count = 4 }, { id = 11475, count = 1 } },
		requiredKills = 80,
		creatures = { "necromancer", "blood priest", "blood hand", "priestess" },
		exp = 30000,
		money = 6000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Ogres",
		items = { { id = 22188, count = 3 }, { id = 22189, count = 2 } },
		requiredKills = 70,
		creatures = { "ogre shaman", "ogre brute", "ogre savage" },
		exp = 75000,
		money = 9000,
		tibiaCoins = 3,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Pirates",
		items = { { id = 10302, count = 12 } },
		requiredKills = 120,
		creatures = {
			"pirate skeleton",
			"pirate marauder",
			"pirate cutthroat",
			"pirate buccaneer",
			"pirate corsair",
		},
		exp = 50000,
		money = 8000,
		tibiaCoins = 2,
		min = 30,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Wyverns",
		items = { { id = 9644, count = 6 } },
		requiredKills = 60,
		creatures = { "wyvern" },
		exp = 34000,
		money = 6000,
		tibiaCoins = 2,
		min = 30,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Wyrms",
		items = { { id = 9665, count = 8 } },
		requiredKills = 50,
		creatures = { "wyrm", "elder wyrm" },
		exp = 50000,
		money = 5000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Earth Elementals",
		items = { { id = 10305, count = 8 } },
		requiredKills = 80,
		creatures = { "earth elemental", "massive earth elemental" },
		exp = 40000,
		money = 8000,
		tibiaCoins = 2,
		min = 30,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Roaring Lions",
		items = { { id = 9691, count = 10 } },
		requiredKills = 60,
		creatures = { "roaring lion" },
		exp = 20000,
		money = 2000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Heroes",
		items = { { id = 11510, count = 2 } },
		requiredKills = 50,
		creatures = {
			"hero",
			"vicious squire",
			"vile grandmaster",
			"renegade knight",
		},
		exp = 45000,
		money = 5000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Giant Spiders",
		items = { { id = 5879, count = 1 } },
		requiredKills = 50,
		creatures = { "giant spider" },
		exp = 55000,
		money = 6500,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Faes",
		items = { { id = 25693, count = 5 }, { id = 25696, count = 5 } },
		requiredKills = 90,
		creatures = {
			"boogy",
			"dark faun",
			"faun",
			"nymph",
			"pixie",
			"pooka",
			"swan maiden",
			"twisted pooka",
		},
		exp = 70000,
		money = 3000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Worker Golems",
		items = { { id = 9655, count = 1 } },
		requiredKills = 50,
		creatures = { "worker golem" },
		exp = 80000,
		money = 7000,
		tibiaCoins = 3,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Mutated Rats",
		items = { { id = 9668, count = 3 } },
		requiredKills = 60,
		creatures = { "mutated rat" },
		exp = 30000,
		money = 6000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	}, -- 120+ lvl
	{
		name = "Behemoths",
		items = { { id = 11447, count = 5 } },
		requiredKills = 50,
		creatures = { "behemoth" },
		exp = 150000,
		money = 10000,
		tibiaCoins = 3,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Brimstone Bugs",
		items = { { id = 11703, count = 8 }, { id = 11702, count = 5 } },
		requiredKills = 70,
		creatures = { "brimstone bug" },
		exp = 75000,
		money = 4000,
		tibiaCoins = 2,
		min = 60,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Demons",
		items = { { id = 5954, count = 3 } },
		requiredKills = 30,
		creatures = { "demon" },
		exp = 200000,
		money = 10000,
		tibiaCoins = 2,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	}, -- can be completed once since 120 lvl
	{
		name = "Destroyers",
		items = { { id = 10298, count = 3 } },
		requiredKills = 50,
		creatures = { "destroyer" },
		exp = 150000,
		money = 15000,
		tibiaCoins = 3,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Drakens",
		items = { { id = 10404, count = 3 }, { id = 10397, count = 3 } },
		requiredKills = 70,
		creatures = {
			"draken abomination",
			"draken elite",
			"draken spellweaver",
			"draken warmaster",
		},
		exp = 180000,
		money = 10000,
		tibiaCoins = 2,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Frost Dragons",
		items = { { id = 9661, count = 1 } },
		requiredKills = 50,
		creatures = { "frost dragon", "frost dragon hatchling", "ice dragon" },
		exp = 110000,
		money = 10000,
		tibiaCoins = 2,
		min = 60,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Dragon Lords",
		items = { { id = 5948, count = 2 } },
		requiredKills = 50,
		creatures = { "dragon lord", "dragon lord hatchling" },
		exp = 110000,
		money = 10000,
		tibiaCoins = 2,
		min = 60,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Hellhounds",
		items = { { id = 16131, count = 1 }, { id = 9636, count = 1 } },
		requiredKills = 20,
		creatures = { "hellhound" },
		exp = 250000,
		money = 10000,
		tibiaCoins = 3,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Hellspawns",
		items = { { id = 10304, count = 5 } },
		requiredKills = 50,
		creatures = { "hellspawn" },
		exp = 150000,
		money = 10000,
		tibiaCoins = 2,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "High Lizards",
		items = { { id = 10416, count = 1 }, { id = 10444, count = 1 } },
		requiredKills = 60,
		creatures = {
			"lizard legionnaire",
			"lizard dragon priest",
			"lizard high guard",
			"lizard zaogun",
			"lizard chosen",
		},
		exp = 100000,
		money = 10000,
		tibiaCoins = 2,
		min = 60,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Killer Caimans",
		items = { { id = 10279, count = 12 } },
		requiredKills = 60,
		creatures = { "killer caiman" },
		exp = 60000,
		money = 6000,
		tibiaCoins = 2,
		min = 60,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Medusas",
		items = { { id = 10309, count = 3 } },
		requiredKills = 40,
		creatures = { "medusa" },
		exp = 160000,
		money = 10000,
		tibiaCoins = 2,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Nightmares",
		items = { { id = 10312, count = 3 } },
		requiredKills = 50,
		creatures = { "nightmare", "nightmare scion" },
		exp = 160000,
		money = 10000,
		tibiaCoins = 2,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Quaras",
		items = {
			{ id = 11490, count = 2 },
			{ id = 11489, count = 2 },
			{ id = 11487, count = 2 },
		},
		requiredKills = 60,
		creatures = {
			"quara constrictor",
			"quara hydromancer",
			"quara hydromancer scout",
			"quara mantassin",
			"quara pincher",
			"quara pincher scout",
			"quara predator",
			"quara predator scout",
		},
		exp = 120000,
		money = 9000,
		tibiaCoins = 3,
		min = 60,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Sea Serpents",
		items = { { id = 9666, count = 5 } },
		requiredKills = 50,
		creatures = { "sea serpent", "young sea serpent" },
		exp = 100000,
		money = 5000,
		tibiaCoins = 2,
		min = 60,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Hydras",
		items = { { id = 10282, count = 5 } },
		requiredKills = 50,
		creatures = { "hydra" },
		exp = 150000,
		money = 10000,
		tibiaCoins = 2,
		min = 60,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Undead Dragons",
		items = { { id = 10316, count = 3 } },
		requiredKills = 30,
		creatures = { "undead dragon" },
		exp = 333000,
		money = 10000,
		tibiaCoins = 3,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Ghastly Dragons",
		items = { { id = 10449, count = 3 } },
		requiredKills = 30,
		creatures = { "ghastly dragon" },
		exp = 250000,
		money = 10000,
		tibiaCoins = 2,
		min = 60,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Asuras",
		items = { { id = 21974, count = 10 }, { id = 21975, count = 10 } },
		requiredKills = 60,
		creatures = {
			"dawnfire asura",
			"midnight asura",
			"frost flower asura",
			"true dawnfire asura",
			"true midnight asura",
			"true frost flower asura",
		},
		exp = 130000,
		money = 10000,
		tibiaCoins = 2,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Frazzles",
		items = { { id = 20198, count = 8 }, { id = 20199, count = 7 } },
		requiredKills = 50,
		creatures = { "frazzlemaw", "guzzlemaw" },
		exp = 180000,
		money = 10000,
		tibiaCoins = 2,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Lycanthropes",
		items = {
			{ id = 22051, count = 4 },
			{ id = 22052, count = 4 },
			{ id = 22054, count = 4 },
		},
		requiredKills = 70,
		creatures = {
			"werewolf",
			"werebadger",
			"werebear",
			"wereboar",
			"werefox",
		},
		exp = 140000,
		money = 10000,
		tibiaCoins = 2,
		min = 60,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Glooth Bandits",
		items = { { id = 21816, count = 3 } },
		requiredKills = 60,
		creatures = { "glooth bandit", "glooth brigand" },
		exp = 150000,
		money = 10000,
		tibiaCoins = 2,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Shaburak Demons",
		items = { { id = 3030, count = 5 } },
		requiredKills = 40,
		creatures = { "shaburak demon", "shaburak lord", "shaburak prince" },
		exp = 50000,
		money = 5000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Askarak Demons",
		items = { { id = 3032, count = 5 } },
		requiredKills = 40,
		creatures = { "askarak demon", "askarak lord", "askarak prince" },
		exp = 50000,
		money = 5000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Putrid Mummies",
		items = { { id = 25697, count = 4 } },
		requiredKills = 40,
		creatures = { "putrid Mummy" },
		exp = 40000,
		money = 3000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Banshees",
		items = { { id = 11446, count = 1 } },
		requiredKills = 30,
		creatures = { "banshee" },
		exp = 30000,
		money = 3000,
		tibiaCoins = 2,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Lost Dwarves",
		items = { { id = 17855, count = 2 }, { id = 12600, count = 4 } },
		requiredKills = 60,
		creatures = { "lost basher", "lost husher", "lost exile", "lost thrower" },
		exp = 80000,
		money = 8000,
		tibiaCoins = 3,
		min = 50,
		max = NO_MAX_LEVEL_LIMIT,
	},
	{
		name = "Weak Cults",
		items = { { id = 9638, count = 1 }, { id = 9639, count = 2 } },
		requiredKills = 50,
		creatures = { "novice of the cult", "adept of the cult", "acolyte of the cult", "enlightened of the cult" },
		exp = 40000,
		money = 3000,
		tibiaCoins = 2,
		min = 30,
		max = 120,
	},
	{
		name = "Ice Witches",
		items = { { id = 7441, count = 3 } },
		requiredKills = 50,
		creatures = { "ice witch" },
		exp = 40000,
		money = 3000,
		tibiaCoins = 2,
		min = 30,
		max = 120,
	},
	{
		name = "Other Dimension",
		items = { { id = 23510, count = 2 }, { id = 23518, count = 2 } },
		requiredKills = 30,
		creatures = { "sparkion", "breach brood", "reality reaver", "dread intruder" },
		exp = 80000,
		money = 8000,
		tibiaCoins = 3,
		min = 120,
		max = NO_MAX_LEVEL_LIMIT,
	},
}

local creatureNameToDailyTask = {}
local storageToDailyTask = {}

function GetDailyTaskByStorage(storage)
	return storageToDailyTask[storage]
end
function GetDailyTaskByCreatureName(creatureName)
	return creatureNameToDailyTask[creatureName]
end
function GetAllDailyTasks()
	return dailyTasksData
end
local function setAuxillaryMaps(dailyTask, i)
	storageToDailyTask[dailyTask.storage] = dailyTasksData[i]
	for _, creatureName in pairs(dailyTask.creatures) do
		creatureNameToDailyTask[creatureName] = dailyTasksData[i]
	end
end

local taskTaskNameScope = Scope("DailyTask", "TaskName")
local taskCurrentKillsScope = Scope("DailyTask", "CurrentKills")
function RegisterDailyTasksInQuestsTable()
	for i, dailyTask in pairs(dailyTasksData) do
		local storage = taskTaskNameScope:Get(dailyTask.name)
		local currentKills = taskCurrentKillsScope:Get(dailyTask.name)

		dailyTask.storage = storage
		dailyTasksData[i].storage = storage
		dailyTask.currentKills = currentKills

		local dailyTaskMission = {
			name = "DAILY_TASK_MISSION_NAME",
			dailyTask = dailyTasksData[i],
			storage = storage,
			minValue = 0,
			description = "DAILY_TASK_MISSION_DESCRIPTION",
		}

		setAuxillaryMaps(dailyTask, i)
		table.insert(DailyTaskQuestlog.missions, dailyTaskMission)
	end
end
