return {
	["Listen, I've finished exploring holes, and now I have a different passion. If you want to help me, listen up. Some time ago, I got a job as a TV presenter, and I still have that job. Unfortunately, the salary is not entirely satisfactory. I found out that one of the fortune tellers hosting some show on the network where I work has been quarantined. The station is now looking for a replacement for his position, and I think I'm suited for it - I have a degree in quackery, but I'll need a few props. Are you ready to help me?"] = "Sluchaj, ja z eksploracja dziur skonczylem i mam teraz inna pasje. Jesli chcesz mi pomoc, to sluchaj. Jakis czas temu zatrudnilem sie jako prezenter telewizyjny, i do teraz mam ten etat. Niestety pensja jest niezupelnie zadowalajaca. Dowiedzialem sie, ze ktorys z wrozbitow, prowadzacych jakis program w sieci, w ktorej jestem zatrudniony, zostal przeniesiony na kwarantanne. Stacja teraz szuka zastepstwa na jego stanowisko, i mysle ze sie do tego nadam. Z hochsztaplerstwa mam doktorat, ale bede potrzebowal jeszcze kilku rekwizytow. Czy jestes gotow mi pomoc?",
	["Great. I need a Magic Light Wand to blind viewers with false promises. A Magician's Robe to look like a magician. A crystal ball with a small hole... just find a round aquarium. Lastly, I need a life crystal. If you gather these items, come back to me."] = "Swietnie. Potrzebuje Magic Light Wand do swiecenia staremu. Magician's Robe, zeby wygladac jak mag. Krysztalowa kule z dziurka na... po prostu znajdz okragle akwarium. Na koniec potrzebuje life crystal. Jezeli zbierzesz te przedmioty, to wroc do mnie",
	["The lid of this coffin won't move at all."] = "Wieko trumny ani drgnie.",
	["Doubling your efforts, you managed to move the lid a bit."] = "Uzywajac zdwojonej sily udalo Ci sie lekko poruszyc wiekiem trumny.",
	["Having noticed nearby crobar, you put it in cracks in the wood and try to pry it, but the very fragment of wood was rotten and broke off."] = "Zapierajac pobliski lom o szczeline podpierasz wieko, ale kawalek drewna, ktory podwazales, odlamal sie.",
	["You relocate crowbar to another crevice nad using all you strength, you broke off the lid."] = "Ustawiles lom w innym miejscu, i uzywajac calej swojej sily, udalo Ci sie podwazyc i zsunac wieko.",
	["Bildo's last will"] = "Testament Bildo",
	["[...]this is the part of the will concerning my grandson. Back in 2014 me and my company broke our way into the down syndrome pyramid. When we were deep down there, something grabbed onto Gwindel. In no time, he already fell to his death and was lying in the corner of the pyramid. Unfortunately, he was descending first, thus he was the one using the magical torch. This is the heirloom 'Im entrusting to you. Entrance to the pyramid is located in fuck fuck fuckity fuck. You should remember things like this. The only requirement for you to be able to acquire this part of heritage is being at least 32 years old.\n\nSigned by Bildo\n\nP.S. Chester is a mountebank and swindler"] = "[...]ta czesc testamentu tyczy sie mojego wnuka. W 2014 roku wlamalem sie do piramidy labiryntu downa wraz z moja kompania. Gdy bylismy juz w jej glebi, cos zlapalo Gwindela. Zanim sie obejrzelismy, lezal on na dnie wyrwy w piramidzie z roztrzaskana czaszka. Niestety, to on schodzil jako pierwszy i oswietlal nam droge magiczna pochodnia. Wlasnie te pochodnie zostawiam Ci w spadku. Wejscie do grobowca znajduje sie w PIZDZIE KURWA. Powiniennes pamietac takie rzeczy. Jedyny warunek jaki musisz spelnic, aby moc ja podniesc to osiagniecie wieku 32 lat. Podpisano: Bildo. P.S. Czeslaw to oszust i zlodziej",
	["Contract of service. Signed on the day of 20 IV 2014 in the free city of Hurghada. An agreement between Bildo, Chester the Dwarf, Gwindel and Gandalf. [...]"] = "Umowa o dzielo. Kontrakt zawarty w dniu 20 IV 2014 w Orshaawa, pomiedzy Bildo a Czeslaw Krasnolud, Gwindel i Gandalf. [...]",
	["Grave Digger's crowbar for special usage."] = "Specjalny lom od Grave Diggera.",
	["You found out what happened to one of the survivors."] = "Doweidziales sie co sie stalo ze wszystkimi ocalalymi.",
	-- Im Resting Herea
	["Im Resting Here"] = "Spoczywajacy Tutaj",
	["A Work to Screw up"] = "Robotka do spierdolenia",
	["Grave digger gave you a special crowbar. Try to find a use for it."] = "Grave digger dal ci specjalny lom. Sproboj znalezc dla niego zastosowanie.",
	["You found some kind of last will. Try to find the item mentioned in it."] = "Znalazles cos, co wyglada na testament, a w nim opis drogi do mitycznego labiryntu downa. Udaj sie w miejsce opisane w dokumencie..",
	["You found a document that indicates that four people broke into the labyrinth. At least two of them are no longer alive. Try to find one of the survivors."] = "Znalazles dokument, ktory wskazuje, iz cztery osoby wlamaly sie do labiryntu. Co najmniej dwoje z nich nie zyje. Sprobuj znalezc ktoregos z ocalalych.",
	
}
