return {
	["Hello. What brings you here?"] = "Hello. What brings you here?",
	["It was many years ago. One day, in Mirkotown, the Undead King of the Crypt appeared, causing havoc among our residents. The city slowly turned into a ruin until 9:37 PM when one of the houses was blown up using dark magic. In that same house, there was a laundry basket, and inside it, a holy relic - socks with John Paul, which flew and landed in the hands of the Crypt King. At that moment, he howled with a demonic voice, 'ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ' and immediately became paralyzed. Without a second thought, all defenders gathered to seal his soul. On the same day, we locked his soul in the banshee cave. The remains of his body were scattered across the desert to prevent any attempts at reanimation. I thought his spirit would be neutralized in the cave, but as I recently found out, he managed to escape from there. I don't know how strong he is right now, but he will surely try to regenerate. We must ultimately destroy him! It won't be an easy task, and before I entrust it to you, you will need to prove to me that you are worthy of leading this crusade. Return to me when you fulfill all my {conditions}."] = "It was many years ago. One day, in Mirkotown, the Undead King of the Crypt appeared, causing havoc among our residents. The city slowly turned into a ruin until 9:37 PM when one of the houses was blown up using dark magic. In that same house, there was a laundry basket, and inside it, a holy relic - socks with John Paul, which flew and landed in the hands of the Crypt King. At that moment, he howled with a demonic voice, 'ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ' and immediately became paralyzed. Without a second thought, all defenders gathered to seal his soul. On the same day, we locked his soul in the banshee cave. The remains of his body were scattered across the desert to prevent any attempts at reanimation. I thought his spirit would be neutralized in the cave, but as I recently found out, he managed to escape from there. I don't know how strong he is right now, but he will surely try to regenerate. We must ultimately destroy him! It won't be an easy task, and before I entrust it to you, you will need to prove to me that you are worthy of leading this crusade. Return to me when you fulfill all my {conditions}.",
	["It's interesting that you know our password. Nevertheless, I have no task for you or anything to interest you with."] = "It's interesting that you know our password. Nevertheless, I have no task for you or anything to interest you with.",
	["Welcome again. Are you ready to accept my {conditions}?"] = "Welcome again. Are you ready to accept my {conditions}?",
	["Allakhazam!!!1. Oh, wait, that's not all. I forgot that you also need to visit the magic circles. Each circle consists of 6 stones in 3 different colors, with a special grid in the middle. Stand on all five grids, and I will be able to bless you. I won't tell you where the circles are because you can ask the owners of magic shops in towns about it. Talk to them, and they will guide you to the circles. Just write 'circle' to them, and they will explain everything to you."] = "Allakhazam!!!1. Oh, wait, that's not all. I forgot that you also need to visit the magic circles. Each circle consists of 6 stones in 3 different colors, with a special grid in the middle. Stand on all five grids, and I will be able to bless you. I won't tell you where the circles are because you can ask the owners of magic shops in towns about it. Talk to them, and they will guide you to the circles. Just write 'circle' to them, and they will explain everything to you.",
	["My conditions are to complete the following tasks: Druid Path, Yalahar Quest. While you know the secret password, I also want other druids and elves to vouch for you. Additionally, you must visit at least one poi throne. If you are ready, ask me again about {conditions}."] = "My conditions are to complete the following tasks: Druid Path, Yalahar Quest. While you know the secret password, I also want other druids and elves to vouch for you. Additionally, you must visit at least one poi throne. If you are ready, ask me again about {conditions}.",
	["Hocus Pocus! Now everything should work. Something very dark lurks in the pyramid's underground. Ask Konmuld for advice, and maybe you will escape from there alive. Oh, I almost forgot: from now on, you can now use the sealed doors in the pyramid."] = "Hocus Pocus! Now everything should work. Something very dark lurks in the pyramid's underground. Ask Konmuld for advice, and maybe you will escape from there alive. Oh, I almost forgot: from now on, you can now use the sealed doors in the pyramid.",
	["Ask the individual owners of magic shops about the locations of the circles."] = "Ask the individual owners of magic shops about the locations of the circles.",
	["Here is your reward for your effort. Wait, wait... where is my backpack!? It was probably Chester doing. Well, I guess your bonus reward is gone."] = "Here is your reward for your effort. Wait, wait... where is my backpack!? It was probably Chester doing. Well, I guess your bonus reward is gone.",
	["You step on circle number "] = "You step on circle number ",
	["To fulfill Gandalf's ordeal, you need to stand on "] = "To fulfill Gandalf's task you need to stand on ",
	[" remaining circles."] = " remaining circles.",
	["If you really know what danger he is, deal with his ally first - Sultan of Phantasms. Also deal with that swindler, Chester, who tried to fuck me over in Down's Labyrinth."] = "If you really know what danger he is, deal with his ally first - Sultan of Phantasms. Also deal with that swindler, Chester, who tried to fuck me over in Down's Labyrinth.",
	-- Path of the Undead
	["Path of the Undead"] = "Path of the Undead",
	["Test of Strength"] = "Test of Strength",
	["Gandalf told you about the history of Mirkotown. Now, ask him what conditions you need to fulfill to get his help."] = "Gandalf told you about the history of Mirkotown. Now, ask him what conditions you need to fulfill to get his help.",
	["Gandalf promised to bless your cause, but first, you must visit special magical circles."] = "Gandalf promised to bless your cause, but first, you must visit special magical circles.",
	["Endurance Test"] = "Endurance Test",
	["Gandalf has blessed you and advised you to go to Konmuld for further instructions."] = "Gandalf has blessed you and advised you to go to Konmuld for further instructions.",
	["The Final Battle"] = "The Final Battle",
	["Gather the necessary items, summon, and ultimately defeat the Undead Crypt King."] = "Gather the necessary items, summon, and ultimately defeat the Undead Crypt King.",
	["You have defeated the Undead Crypt King. Return to Gandalf for your reward."] = "You have defeated the Undead Crypt King. Return to Gandalf for your reward.",
	["Gandalf misplaced a certain item intended as a reward, but you have received his other gifts."] = "Gandalf misplaced a certain item intended as a reward, but you have received his other gifts.",
	["King of Rats Headquarters Status"] = function(context)
		local result = -1
		for _, storage in pairs(Storage.KingOfRatsHQ.Portals) do
			local value = context.player:getStorageValue(storage)
			if value == 1 then
				result = result + 1
			end
		end
		return string.format("So far you have collected %d artifacts.", result)
	end,
}
