return {
	["How do you know? Did you go into the infested area?"] = "How do you know? Did you go into the infested area?",
	["You better don't return here until you've defeated the Demon Oak. Perhaps you lost your {axe}?"] = "You better don't return here until you've defeated the Demon Oak. Perhaps you lost your {axe}?",
	["You chopped down the demon oak?!? Unbelievable!! Let's hope it doesn't come back. As long as evil is still existent in the soil of the plains, it won't be over. Still, the demons suffered a setback, that's for sure. ...\n\nFor your brave action, I tell you a secret which has been kept for many many years. There is an old cemetery in the south east from elvish court, far south from Mirko Town. There should be a grave with the name 'Grdhor Faelyn' somewhere. ...\n\nSomeone can gain the treasure hidden in there. I'm sure this 'someone' is you. Good luck in finding it!"] = "You chopped down the demon oak?!? Unbelievable!! Let's hope it doesn't come back. As long as evil is still existent in the soil of the plains, it won't be over. Still, the demons suffered a setback, that's for sure. ...\n\nFor your brave action, I tell you a secret which has been kept for many many years. There is an old cemetery in the south east from elvish court, far south from Mirko Town. There should be a grave with the name 'Grdhor Faelyn' somewhere. ...\n\nSomeone can gain the treasure hidden in there. I'm sure this 'someone' is you. Good luck in finding it!",
	["A demon oak?!? <mumbles some blessings> May the gods be on our side. You'll need a {hallowed axe} to harm that tree. Bring me a simple {axe} and I'll prepare it for you."] = "A demon oak?!? <mumbles some blessings> May the gods be on our side. You'll need a {hallowed axe} to harm that tree. Bring me a simple {axe} and I'll prepare it for you.",
	["Ahh, you've got an axe. Very good. I can make a hallowed axe out of it. It will cost you... er... a donation of 1,000 gold. Alright?"] = "Ahh, you've got an axe. Very good. I can make a hallowed axe out of it. It will cost you... er... a donation of 1,000 gold. Alright?",
	["Let's see....<mumbles a prayer>....here we go. The blessing on this axe will be absorbed by all the demonic energy around here. I presume it will not last very long, so better hurry. Actually, I can refresh the blessing as often as you like."] = "Let's see....<mumbles a prayer>....here we go. The blessing on this axe will be absorbed by all the demonic energy around here. I presume it will not last very long, so better hurry. Actually, I can refresh the blessing as often as you like.",
	["You dont have an axe."] = "You dont have an axe.",
	["What a pity! Let me know when you managed to get in there. Maybe I can help you when we know what we are dealing with."] = "What a pity! Let me know when you managed to get in there. Maybe I can help you when we know what we are dealing with.",
	--Questlog
	["Demon Oak"] = "Demon Oak",
	["You have made your way into the den of Demon Oak. Try to find someone who will tell you more about it."] = "You have made your way into the den of Demon Oak. Try to find someone who will tell you more about it.",
	["Oldrak gave you information regarding Demon Oak. He can bless an axe if you bring him one. The blessed axe should help you fight the Oak."] = "Oldrak gave you information regarding Demon Oak. He can bless an axe if you bring him one. The blessed axe should help you fight the Oak.",
	["You defeated the Demon Oak! Report to Oldrak."] = "You defeated the Demon Oak! Report to Oldrak.",
	["You reported to Oldrak about your victory. You have been rewarded for your efforts: Oldrak told you a secret about the way to the Elvish treasury."] = "You reported to Oldrak about your victory. You have been rewarded for your efforts: Oldrak told you a secret about the way to the Elvish treasury.",
	["You found and took your reward for defeating The Demon Oak."] = "You found and took your reward for defeating The Demon Oak.",
}
