return {
	["Kraken"] = "The fight starts with the leader looking through the telescope to realize that the kraken is attacking your ship!\nKraken tentacles want to destroy ship's hull and board. Block their attacks with your body to delay your demise.\nWhile on ship, you can attack some of the tentacles. Damaging them will also damage the kraken itself later.\nAfter some time you wont be able to keep up with tentacles, and your ship will be turned to wreckage. The kraken will emerge from the depths to attack you. This will we your chance to strike him directly.",
	["Zul Szczurow"] = "The Zul Szczurow itself is harmless. You should be careful when dealing with his henchman - Zul Zulow.\nZul Zulow has very low health pool, but when dying, it summons two of its brothers. Be careful, as their number can skyrocket very fast!\nThe longer the time since last Zul Zulow death, the more damage they will all deal.",
	["HF-P/X"] = "The main danger here is his army of passat wagons. He will randomly open gates from which the wagons will emerge.\nBe careful not to stand in their way! They also damge HF-P/X itself, so consider baiting him into being hit by them",
	["King of the Crypt"] = "His main power is ever increasing damage when focusing the same target. You should make him change his target if damage is overwhelming. If you do, he will summon a bomb that will deal massive damage to everyone in arena. However, if you stand next to the bomb, this damage will be split amongs closest people.\nHe will also announce and fire dark energy beams. Be careful, as there will be more beams when he is below half health.\nHis last ability is summoning volatile undeads. They dont do anything special other than exploding for big damage on death.",
	["Pol"] = "The white and black tiles are daming you whenever you are on tile with color other that boss's. The more times you fail to stand on same color, the more damage this will inflict.\nThis boss also has deadly plus shaped attack, so you should be always ready to move!",
	["Skurwiwij"] = "He is constantly draining elemental power from a nearby pylon, or pylons in case both are in same distance.\nIf a new pylon becomes the nearest one, drained power of previous pylon is reset. After that, the furthest pylon explodes.\nYou have to switch between pylons when his elemental damage becomes unbearable. Be careful not to do it too often, as each next pylon explosion is stronger.",
	["Ruk'ca Maw"] = "The start is very rough. Ruk'ca is very hungry and will try to consume anything. Move him to the cages, so he eats a baby seal and calms down... for a moment. Do it fast, as his fury is gonna ramp up constantly.\nWhile moving through his tunnels, you have to finally move him to the piles of salt at the end of cave. He is allergic to it.",
}
