return {
    ["When I was still living in MirkoTown I've seen place where guards are going for a brake, they are sitting around campfire and rest there.\nSet the tree on fire near them, they will get mad for sure.\nAre you down for that?"] = "When I was still living in MirkoTown I've seen place where guards are going for a brake, they are sitting around campfire and rest there.\nSet the tree on fire near them, they will get mad for sure.\nAre you down for that?",
    ["Just don't go there during their lunch break, I don't have more beds xD."] = "Just don't go there during their lunch break, I don't have more beds xD.",
    ["That tree is located near the west gate."] = "That tree is located near the west gate.",
    ["Too bad that I won't be seeing their faces when they will find out.\nYou're getting better. If you need more just come back! Take this staff that of the real smoker!"] = "Too bad that I won't be seeing their faces when they will find out.\nYou're getting better. If you need more just come back! Take this staff that of the real smoker!",
    ["Once e and my fellas we were having fun and we planted some toxic flowers in Mirkotown, some of them were beyond city walls.\nSadly I am not able to tell you which ones exactly because they look like normal red flowers. \nIf you burn them the whole city will be high, would you do that?"] = "Once e and my fellas we were having fun and we planted some toxic flowers in Mirkotown, some of them were beyond city walls.\nSadly I am not able to tell you which ones exactly because they look like normal red flowers. \nIf you burn them the whole city will be high, would you do that?",
    ["Yo, |PLAYERNAME|! You want to {smoke} some?"] = "Yo, |PLAYERNAME|! You want to {smoke} some?",
    ["We planted total of 5 flowers. You have o search in mirkotown and maybe in its closest vicinities."] = "We planted total of 5 flowers. You have o search in mirkotown and maybe in its closest vicinities.",
    ["Ohh Yes, I would burn something, maybe those rats from Mirkotown? They evicted me for my pyrotechnic tendencies. ...\nWanna set somethin' on fire?"] = "Ohh Yes, I would burn something, maybe those rats from Mirkotown? They evicted me for my pyrotechnic tendencies. ...\nWanna set somethin' on fire?",
    ["If you want to play a little bit, go and burn some weed which I left in my house. Better for me if guards won't find it otherwise I'll have to run away. ...\n\nI can't show myself in the city, my cottage is located in the north of the city, you will recognize it immediately. ...\n\nHave this fire bug, you'll need it."] = "If you want to play a little bit, go and burn some weed which I left in my house. Better for me if guards won't find it otherwise I'll have to run away. ...\n\nI can't show myself in the city, my cottage is located in the north of the city, you will recognize it immediately. ...\n\nHave this fire bug, you'll need it.",
    ["Last time i checked, my house was at north gate of Mirkotown."] = "Last time i checked, my house was at north gate of Mirkotown.",
    ["It was great! I already can see that smoke I'll be breathing in.\nTake this weapon for your achievements, you will be able to burn more stuff with it.\nThat was fun! See you!"] = "It was great! I already can see that smoke I'll be breathing in.\nTake this weapon for your achievements, you will be able to burn more stuff with it.\nThat was fun! See you!",
    ["It burns so nice, word. I'm hoping that guards won't get too high xD\nI see that you liked it, if you want to burn some more just {ask}. You can keep the lighter if it hasn't exploded yet."] = "It burns so nice, word. I'm hoping that guards won't get too high xD\nI see that you liked it, if you want to burn some more just {ask}. You can keep the lighter if it hasn't exploded yet.",
    ["I knew i can count on you. Just be careful with that stuff!"] = "I knew i can count on you. Just be careful with that stuff!",
    
}
