SPRAWIEDLIWY_WOBEC_NARODOW_MONSTER_NAMES = {
	[0] = "Zbrodniarz",
	[1] = "Oprawca",
	[2] = "Ciemiezca",
	[3] = "Ciemiezyciel",
	[4] = "Tyran", --
	[5] = "Len",
	[6] = "Bezmozg", --
	[7] = "Niewdziecznik",
	[8] = "Zasraniec",
	[9] = "Bezczelnik",
	[10] = "Niespokojec", --
	[11] = "Pierdolony gnojownik", --
	[12] = "Jebaniec", --
	[13] = "Chytrus", --
	[14] = "Gnebiciel",
	[15] = "Damski bokser",
	[16] = "Nieudacznik",
	[17] = "Mimo ze dzieci w afryce gloduja",
	[18] = "Szubrawiec",
	[19] = "Morderca",
}
