JOB_TRADE_REQUEST_RESPONSE = {
	[JOB_NONE] = { text = "Of course, just browse through my wares." },
	[JOB_DISTANCE_SOULORB] = { text = "Of course, just browse through my wares." },
	[JOB_ARMOR_WEAPON] = { text = "Of course, just browse through my wares." },
	[JOB_MAGIC_WILDCARD] = { text = "Of course, just browse through my wares." },
	[JOB_MAGIC] = { text = "Of course, just browse through my wares." },
	[JOB_CREATURE_PRODUCT] = { text = "Of course, just browse through my wares." },
	[JOB_FURNITURE] = { text = "Of course, just browse through my wares." },
	[JOB_JEWELLER] = { text = "Of course, just browse through my wares." },
	[JOB_UTILITY] = { text = "Of course, just browse through my wares." },
	[JOB_DAILYTASKS_GOLDENOUTFIT] = { text = "Of course, just browse through my wares." },
	[JOB_FISHER] = { text = "Of course, just browse through my wares." },
	[JOB_SOFT_BOOTS_RECHARGE] = { text = "Of course, just browse through my wares." },
	[JOB_FOOD] = { text = "Of course, just browse through my wares." },
	[JOB_TASKS_IMBUING] = { text = "Of course, just browse through my wares." },
	[JOB_AOL] = { text = "Of course, just browse through my wares." },
	[JOB_POST] = { text = "Of course, just browse through my wares." },
	[JOB_BANK] = { text = "Of course, just browse through my wares." },
}
