ENCOUNTER_ERROR_CODES = {
	NO_ERROR = "NO_ERROR",
	SOMEONE_HAS_NO_ACCESS = "SOMEONE_HAS_NO_ACCESS",
	YOU_HAVE_NO_ACCESS = "YOU_HAVE_NO_ACCESS",
	SOMEONE_HAS_LOCKOUT = "SOMEONE_HAS_LOCKOUT",
	YOU_HAVE_LOCKOUT = "YOU_HAVE_LOCKOUT",
	YOU_HAVE_TO_WAIT = "YOU_HAVE_TO_WAIT",
	ONLY_PLAYERS = "ONLY_PLAYERS",
	SOMEONE_INSIDE_ALREADY = "SOMEONE_INSIDE_ALREADY",
	-- IN_PROGRESS = "IN_PROGRESS",
	STAND_ON_ENTRANCE = "STAND_ON_ENTRANCE",
	NO_LEVEL = "NO_LEVEL",
	ENCOUNTER_DISABLED = "ENCOUNTER_DISABLED",
}