GLOBAL_EVENT_OK = true

USE_UP = "USE_UP"
USE_DOWN = "USE_DOWN"

MINIGAMES_BROADCAST_TOP_PARTICIPANTS = "MINIGAMES_BROADCAST_TOP_PARTICIPANTS"

MINIGAME_VALIDATION_STATUS = {
	UNVALIDATED = "UNVALIDATED",
	VALIDATED = "VALIDATED",
	VALIDATION_FAIL = "VALIDATION_FAIL",
}

MINIGAME_STAGE = {
	UNSTARTED = -100,
	LOBBY_10MIN_BEFORE = 1,
	LOBBY_5MIN_BEFORE = 2,
	LOBBY_1MIN_BEFORE = 3,
	LOBBY_10SECONDS_BEFORE = 4,
	RUNNING = 100,
}

---@class MINIGAME_COMPETITION_TYPE
MINIGAME_COMPETITION_TYPE = {
	SPEEDRUN = "SPEEDRUN",
	LAST_MAN_STANDING = "LAST_MAN_STANDING",
	OTHER = "OTHER",
}

NO_GROUND_ID = 0
DIFFICULTY_NONE = -1
BASE_ESCORT_MONSTER_NAME = "BASE_ESCORT_MONSTER_NAME"
PERMANENTLY_CLOSED = "PERMANENTLY_CLOSED"
OPEN_CONTAINER_ON_USE = false
DONT_OPEN_CONTAINER_ON_USE = true

ENCOUNTER_ERROR_CODES = {
	NO_ERROR = "NO_ERROR",
	SOMEONE_HAS_NO_ACCESS = "SOMEONE_HAS_NO_ACCESS",
	YOU_HAVE_NO_ACCESS = "YOU_HAVE_NO_ACCESS",
	SOMEONE_HAS_LOCKOUT = "SOMEONE_HAS_LOCKOUT",
	YOU_HAVE_LOCKOUT = "YOU_HAVE_LOCKOUT",
	YOU_HAVE_TO_WAIT = "YOU_HAVE_TO_WAIT",
	ONLY_PLAYERS = "ONLY_PLAYERS",
	SOMEONE_INSIDE_ALREADY = "SOMEONE_INSIDE_ALREADY",
	ENCOUNTER_ACTIVE = "ENCOUNTER_ACTIVE",
	STAND_ON_ENTRANCE = "STAND_ON_ENTRANCE",
	NO_LEVEL = "NO_LEVEL",
	ENCOUNTER_DISABLED = "ENCOUNTER_DISABLED",
	NO_DIFFICULTY_CHOSEN = "NO_DIFFICULTY_CHOSEN",
}

DONT_SHOW_ONLOOK = true
DO_SHOW_ONLOOK = false

KEY_RING_ID = 49279

--#region JOB
JOB_NONE = "JOB_NONE"

JOB_DISTANCE_SOULORB = "JOB_DISTANCE_SOULORB"
JOB_SOULORB = "JOB_SOULORB"
JOB_DISTANCE = "JOB_DISTANCE"

JOB_ARMOR_WEAPON = "JOB_ARMOR_WEAPON"

JOB_MAGIC_WILDCARD = "JOB_MAGIC_WILDCARD"
JOB_MAGIC = "JOB_MAGIC"
JOB_WILDCARD = "JOB_WILDCARD"
JOB_EXERCISE = "JOB_EXERCISE"

JOB_CREATURE_PRODUCT = "JOB_CREATURE_PRODUCT"

JOB_FURNITURE = "JOB_FURNITURE"

JOB_TASKS_IMBUING = "JOB_TASKS_IMBUING"
JOB_TASKS = "JOB_TASKS"
JOB_IMBUING = "JOB_IMBUING"

JOB_JEWELLER = "JOB_JEWELLER"

JOB_UTILITY = "JOB_UTILITY"

JOB_POST = "JOB_POST"

JOB_FOOD = "JOB_FOOD"

JOB_SOFT_BOOTS_RECHARGE = "JOB_SOFT_BOOTS_RECHARGE"

JOB_DAILYTASKS_GOLDENOUTFIT = "JOB_DAILYTASKS_GOLDENOUTFIT"
JOB_DAILYTASK = "JOB_DAILYTASK"
JOB_GOLDENOUTFIT = "JOB_GOLDENOUTFIT"

JOB_FISHER = "JOB_FISHER"

JOB_AOL = "JOB_AOL"

JOB_BANK = "JOB_BANK"

JOB_MARRIAGE_BLESS = "JOB_MARRIAGE_BLESS"
JOB_MARRIAGE = "JOB_MARRIAGE"
JOB_BLESS = "JOB_BLESS"
--#endregion JOB
