dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/Desert_ghosts/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/desert_quest_hub/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/desert_quest_one/_config.lua")

dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/Sultan_prime/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/teatr_taniej_sensacji/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/assassins_creed_skurwoala/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/spoczywajacy_tutaj/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/Czeslaw_krasnolud/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/sciezka_nieumarlych/_config.lua")

dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/krol_szczurow_hub/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/Bezpieczenstwo_i_higiena_pracy/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/Trzej_sramaci_i_smok/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/Tragedya_w_czterech_aktach/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/Per_iustitia_ad_astra/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/Syn_marnotrawny/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/Big_klamoty/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaigu/Sprawiedliwy_wobec_narodow/_config.lua")
