dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/Desert_ghosts/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/desert_quest_hub/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/desert_quest_one/_config.lua")

dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/Sultan_prime/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/teatr_taniej_sensacji/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/assassins_creed_skurwoala/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/spoczywajacy_tutaj/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/Czeslaw_krasnolud/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/sciezka_nieumarlych/_config.lua")

dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/krol_szczurow_hub/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/Bezpieczenstwo_i_higiena_pracy/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/Trzej_sramaci_i_smok/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/Tragedya_w_czterech_aktach/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/Per_iustitia_ad_astra/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/Syn_marnotrawny/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/Big_klamoty/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_vaiguots/Sprawiedliwy_wobec_narodow/_config.lua")
