FROM kuyoh/vcpkg:2024.10.21

# devcontainer setup, see .devcontainer/devcontainer.json
ARG REMOTE_USER
ARG REMOTE_UID
ARG REMOTE_GID

RUN groupmod -n ${REMOTE_USER} ubuntu && \
	usermod -l ${REMOTE_USER} ubuntu

RUN chown -R ${REMOTE_USER}:${REMOTE_USER} /opt/vcpkg
USER ${REMOTE_USER}


RUN mkdir -p /opt/vcpkg/cache
ENV VCPKG_DEFAULT_BINARY_CACHE=/opt/vcpkg/cache
ENV VCPKG_INSTALLED_DIR=/opt/vcpkg/vcpkg_installed

WORKDIR /opt/vcpkg
COPY ../vcpkg.json vcpkg.json
RUN vcpkg install