JOB_DISTANCE_SOULORB = "JOB_DISTANCE_SOULORB"
JOB_SOULORB = "JOB_SOULORB"
JOB_DISTANCE = "JOB_DISTANCE"

JOB_ARMOR_WEAPON = "JOB_ARMOR_WEAPON"

JOB_MAGIC_WILDCARD = "JOB_MAGIC_WILDCARD"
JOB_MAGIC = "JOB_MAGIC"
JOB_WILDCARD = "JOB_WILDCARD"
JOB_EXERCISE = "JOB_EXERCISE"

JOB_CREATURE_PRODUCT = "JOB_CREATURE_PRODUCT"

JOB_FURNITURE = "JOB_FURNITURE"

JOB_TASKS_IMBUING = "JOB_TASKS_IMBUING"
JOB_TASKS = "JOB_TASKS"
JOB_IMBUING = "JOB_IMBUING"

JOB_JEWELLER = "JOB_JEWELLER"

JOB_UTILITY = "JOB_UTILITY"

JOB_POST = "JOB_POST"

JOB_FOOD = "JOB_FOOD"

JOB_SOFT_BOOTS_RECHARGE = "JOB_SOFT_BOOTS_RECHARGE"

JOB_DAILYTASKS_GOLDENOUTFIT = "JOB_DAILYTASKS_GOLDENOUTFIT"
JOB_DAILYTASK = "JOB_DAILYTASK"
JOB_GOLDENOUTFIT = "JOB_GOLDENOUTFIT"

JOB_FISHER = "JOB_FISHER"

JOB_AOL = "JOB_AOL"

JOB_BANK = "JOB_BANK"