dofile(DATA_DIRECTORY .. "/scripts/quests/Desert_ghosts/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/desert_quest_hub/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/desert_quest_one/_config.lua")

dofile(DATA_DIRECTORY .. "/scripts/quests/Sultan_prime/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/teatr_taniej_sensacji/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/assassins_creed_skurwoala/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/spoczywajacy_tutaj/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/Czeslaw_krasnolud/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/sciezka_nieumarlych/_config.lua")

dofile(DATA_DIRECTORY .. "/scripts/quests/krol_szczurow_hub/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/Bezpieczenstwo_i_higiena_pracy/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/Trzej_sramaci_i_smok/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/Tragedya_w_czterech_aktach/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/Per_iustitia_ad_astra/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/Syn_marnotrawny/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/Big_klamoty/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/Sprawiedliwy_wobec_narodow/_config.lua")
