dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/Desert_ghosts/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/desert_quest_hub/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/desert_quest_one/_config.lua")

dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/Sultan_prime/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/teatr_taniej_sensacji/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/assassins_creed_skurwoala/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/spoczywajacy_tutaj/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/Czeslaw_krasnolud/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/sciezka_nieumarlych/_config.lua")

dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/krol_szczurow_hub/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/Bezpieczenstwo_i_higiena_pracy/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/Trzej_sramaci_i_smok/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/Tragedya_w_czterech_aktach/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/Per_iustitia_ad_astra/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/Syn_marnotrawny/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/Big_klamoty/_config.lua")
dofile(DATA_DIRECTORY .. "/scripts/quests/_wykopots/Sprawiedliwy_wobec_narodow/_config.lua")
