return {
	["Hello, |PLAYERNAME|! Lately hardly any people come to visit me"] = "Witaj, |PLAYERNAME|! Ostatnio rzadko ktos mnie odwiedza.",
    ["How do you know? Did you go into the infested area?"] = "Skad o tym wiesz? Wszedles do zarazonej strefy?",
	["You better don't return here until you've defeated the Demon Oak. Perhaps you lost your {axe}?"]="Lepiej tu nie wracaj, nim nie pokonasz Demonicznego Debu. Chyba, ze zapomniales kupic {topor}?",
	["You chopped down the demon oak?!? Unbelievable!! Let's hope it doesn't come back. As long as evil is still existent in the soil of the plains, it won't be over. Still, the demons suffered a setback, that's for sure. ...\n\nFor your brave action, I tell you a secret which has been kept for many many years. There is an old cemetery in the south east from elvish court, far south from Mirko Town. There should be a grave with the name 'Grdhor Faelyn' somewhere. ...\n\nSomeone can gain the treasure hidden in there. I'm sure this 'someone' is you. Good luck in finding it!"] = "Znieszczyles demoniczny dab?!? Niesamowite!! Miejmy nadzieje, ze nie powroci. Do poki ziemia przesiaknieta bedzie zlem, nie mozemy byc pewni wygranej. Mimo wszystko demony poniosly strate, to pewne. ...\n\nDzieki twojemu poczynaniu, wyjawie ci sekret, ktory byl ukrywany przez dziesiatki lat. Musisz udac sie na elficki cmentarz, kilka minut drogi na poludnie od Mirko Town. Na jednym z grobow napisane jest 'Grdhor Faelyn' czy cos takiego. ...\n\nNalezy on do jednego z zasluzonych elfow, ktory polegl na wojnie z orkami. Grob prowadzi do skarbca, gdzie znajduje sie dobytek kilku pokolen jego rodu. Zasluzyles aby przygarnac jeden z przedmiotow, ktore sie tam znajduja. Powodzenia w poszukiwaniu!",
	["A demon oak?!? <mumbles some blessings> May the gods be on our side. You'll need a {hallowed axe} to harm that tree. Bring me a simple {axe} and I'll prepare it for you."] = "Demoniczny Dab?!? Niech bogowie maja nas w opiece. Potrzebowal bedziesz {hallowed axe} aby pokonac to drzewo. Przynies mi zwykle {axe} a przygotuje je specjalnie dla ciebie.",
	["Ahh, you've got an axe. Very good. I can make a hallowed axe out of it. It will cost you... er... a donation of 1,000 gold. Alright?"] = "Masz przy sobie topor?. Moge zrobic z niego hallowed axe. Zaplacisz mi za to... hmm... 1,000 zlota. W porzadku?",
	["Let's see....<mumbles a prayer>....here we go. The blessing on this axe will be absorbed by all the demonic energy around here. I presume it will not last very long, so better hurry. Actually, I can refresh the blessing as often as you like."] = "Zobaczmy... o prosze. Blogoslawienstwa tego topora powinny pochlaniac zla energie. Nie wiem jak dlugo wytrzymaja, wiec lepiej sie pospiesz. Moge zaczarowac go ponownie kiedy tylko zechcesz.",
	["You dont have an axe."] = "Nie masz zadnego topora.",
	["What a pity! Let me know when you managed to get in there. Maybe I can help you when we know what we are dealing with."] = "Daj znac jesli sie tam dostaniesz. Moze pomoge ci jesli dowiem sie z czym mamy do czynienia.",
}
