return {
	["Even strongers potions? Life is not a game, my friend. But if Fisher vouched for you, i suppose i can {teach} you then."] = "Zycie to nie gra, a Ty chcesz wiecej i wiecej? Jesli komisarz Ryba zaswiadcza o twoich umiejetnosciach, to moge cie {nauczyc}.",
	["Good job! Hope you find your new drinking skills useful."] = "Dobra robota! Mam nadzieje ze bedziesz sie delektowac nowymi plynami niczym dzentelmen.",
	["Yes, there are ingredients i was talking about. Now, let me use my ferment-o-matic to instantly create this concoction for you. Take it to the Orshaawa catacombs. When you are there, stand before the door, drink this potion, and the following delirium should allow you to hallucinate yourself going through that door. Inside you shall find what you need to complete your training."] = "Tak, to sa wlasnie skladniki, o ktore prosilem. Pozwol, ze zfermentuje je w moim blyskawicznym termosie. Wez to ze soba. Udaj sie do katakumb w Orshawie. Znajdziesz tam drzwi, ktore nie sposob otworzyc. Wypij wtedy te miksture, a w pijackim zwidzie wyda ci sie, ze przechodzisz przez nie. Za nimi znajdzies cos, co pozwoli ci zakonczyc twoj trening.",
	["I see you have made a great effort to help our city people. For that I would like to thank you personally. Please visit Vislav Shivka, he has a {tactical task} for you, if you know what i mean."] = "Widze, ze przysluzyles sie ludziom w naszym miescie. Chcialbym Ci osobisice podziekowac. Odwiedz prosze Wieslawa Wszywke, gdyz ten przygotowal dla Ciebie {zadanie bojowe}, jesli wiesz o co chodzi.",
	["I learned how to safely drink potions thanks to my excessive drinking habits. You can probably reach same results in 10-15 years. But i suppose you are looking for a faster {method}."] = "Nauczylem sie pic wszelkie mikstury dzieki spozywaniu znacznych ilosci alhokolu. Tobie to zajmie tak z 10-15 lat. Ale podejrzewam, ze szukasz szybszego {sposobu}.",
	["This method was devised by my mentor, sensei Sy-Fu. You have to visit the floating naga temple. Its rumored that they keep their special glowing water there. The temple is located somehwere within unchareted waters.\n\nYou will also need churn of bull's spooge. You can find it at bulltaur canteen.\n\nTake this vial and churn, you will need it to store those liquids. Both of those ingredients will be needed for the next step. Come back when you are done with your task."] = "Ta metoda ujrzala swiatlo dziennie dzieki mojemu mentorowi - sensejowi Sy-Fu. Musisz odwiedzic lewitujaca swiatynie nag. Pogloska mowi, ze trzymaja tam specjalna wode swiecaca. Swiatynia znajduje sie gdzies na nieznanych wodach. Oprocz tego potrzebowac bedziesz rowniez wiadra spuchy. Te ciecz z pewnoscia znajdziesz wsrod Bulltaurow. Wez te oto flaszke oraz wiadro - bedziesz ich potrzebowac w nastepnym kroku. Wroc do mnie, gdy zdobedziesz oba skladniki.",
	["If you would like to expand your vocation expertise, you should meet Vislav Shivka. While he is a master imbiber of magical elixirs himself, he is also capable of teaching his 'craft' to others. Ask him about tactical task and he will surely guide you. Tell him that i sent u there or he might not want to share this knowledge with you. Also take this experience as your reward."] = "Jesli chcesz poszerzyc horyzonty swoich kubkow smakowych, powiniennes spotkac sie z Wieslawem Wszywka. On potrafi wypic wszystko, w dowolnej ilosci, i z pewnoscia bedzie chcial podielic sie swoja wiedza, jesli mu o mnie wspomnisz. Zapytaj go o zadanie bojowe, a na pewno sie zgodzi. Aha, nalezy ci sie tez nagroda w postaci grubego doswiadczenia.",
	["I see that Fisher vouched for you, but i cannot teach you yet. Come back when you are at least level 200."] = "Rozumiem, ze Ryba za ciebie poreczyl, ale nie moge cie jeszce tego nauczyc. Wroc gdy zdobedziesz 200 poziom.",
	--Questlog
	["Enter the Drunk Tank"] = "Wysoka Izba Wytrzezwien",
	["Iron Stomach"] = "Niepowstrzymany Zoladek",
	["Commissioner Fisher told you to ask Vislav Shivka about a tactical task."] = "Komisarz Ryba pokierowal cie do Wieslawa Wszywki, ktory ma dla ciebie bojowe zadanie.",
	["Collect glowing naga water and bull spooge then report to Vislav."] = "Zbierz swiecaca wode nag oraz bycza spuche od bulltaurow, a nastepnie zglos sie do Wieslawa.",
	["Take hallucinogen and step through the sealed doors in Orshaawa catacombs."] = "Spozyj napoj halucynogenny i pokonaj zapieczetowane drzwi w katakumbach Orhsaawy.",
	["You learned how to drink even stronger potions than before. Report to Vislav."] = "Nauczyles sie chclac silniejsze mikstury. Wroc do wieslawa.",
	["Vislav commended you for a job well-done."] = "Wieslaw nagrodzil cie za to, ze dobrze sie spisales.",
}
