return {
	[QuestConstants.FatMyrrusEncounters.EncounterNames.Kraken] = "Walka zaczyna sie od tego, ze dowodca druzyny dostrzega w lunecie, ze wlasnie zaatakowal was kraken!\nJego macki proboja zniszczyc poklad statku. Zablokujcie je swoim cialem, a wasza lajba przezyje dluzej.\nW tym samym czasie mozecie atakowac niektore z jego macek. To oslabi go w nastepnej fazie.\nGdy ilosc macek atakujacych poklad bedzie niepolicznalna, wasz statek zamieni sie w dryfujace deski. Kraken wynurzy wtedy swe plugawe oblicze, a wy bedziecie mogli stawic mu czola twarza w twarz.",
	[QuestConstants.FatMyrrusEncounters.EncounterNames.Zul_Szczurow] = "Zul Szczurow nic nie moze.",
	[QuestConstants.FatMyrrusEncounters.EncounterNames.HFPX] = "W tej walce glownym zagrozeniem beda passaty wypuszcane losowo z bram.\nPassaty sa bardzo niezpieczne, gdyz potraca kazdego, kto bedzie stal na ich drodze. Uzyj ich, aby szybciej zabic HF-P/X, lecz uwazaj, zeby samemu nie wpasc pod kola!",
	[QuestConstants.FatMyrrusEncounters.EncounterNames.King_of_the_Crypt] = "Jego najwieksza moca jest zwiekszanie swojej sily przy atakowaniu wciaz tego samego celu. Powinniscie zmieniac sie co jakis czas. Przy kazdej takiej zmianie krol wyczarowuje bombe, ktora zadaje ogromne obrazenia wszystkim na arenie. Zeby temu zapobiec, stancie przy samej bombie - wtedy obrazenia zostana rownomiernie rozdzielone miedzy osoby stojace obok bomby.\nKrol przywoluje tez szkieletory, ktore wybuchaja przy smierci.",
	[QuestConstants.FatMyrrusEncounters.EncounterNames.Pol] = "Czarne i biale kratki zadaja coraz wiecej obrazen, im dluzej na nich stoisz. Zeby wyzerowac te obrazenia, musisz zejsc z danego koloru na kilka sekund.\nPol potrafi wykonywac obszarowe ataki. Badz czujny i natychmiast ich unikaj!",
	[QuestConstants.FatMyrrusEncounters.EncounterNames.Skurwiwij] = "Skurwiwij pobiera moc z najblizszego fialru. Aby zresetowac moc pobrana z filaru, musisz przeprowadzic bossa do drugiego filaru.\nPrzy zmienie kolumny, poprzednia kolumna wybucha i za kazdym wybuchem obrazenia sa coraz wieksze, wiec nie rob tego za czesto.",
	[QuestConstants.FatMyrrusEncounters.EncounterNames.Ruk_ca_Maw] = "Poczatek walki jest bardzo trudny. Ruk'ca jest glodna i sprobuje zjesc wszystko co sie rusza. Doprowadz ja do klatek, aby zjadla mala foczke. To ja uspokoi... na pewien czas. Lepiej sie pospiesz, bo z wraz z glodem rosnie jej furia.\nProwadz ja do konca jaskini, gdzie znajdzies krysztaly soli, na ktore jest uczulona.",
}
