return {
	["TELEPORTATION_ROD_DESCRIPTION"] = function(context)
		local desc = "Magiczna laska, ktora domniemanie jest wystarczajaco potezna, by przeniesc czesci {lamacza bogow} w bezpieczne miejsce. Obecnie udalo ci sie przetransportowac nastepujace czesci:"
		local player = context.player
		for partCollectedStorage, bossName in pairs(storageToBossName) do
			local state = player:getStorageValueByKey(partCollectedStorage)
			if state == ACCESS_GRANTED then
				desc = desc .. T("\n:bossName:: przetransportowany", { bossName = bossName })
			else
				desc = desc .. T("\n:bossName:: -", { bossName = bossName })
			end
		end
		return desc
	end,
	["Greetings, dear visitor. Please tell me what {brings} you here, to my humble adobe."] = "Witaj, drogi gosciu. Powiedz mi, co cie tu {sprowadza}, do mojej skromnej siedziby.",
	["Ah, you have heard about my search for experienced help. And indeed your reputation for solving certain {problems} has preceded you."] = "Ach, slyszales o moich poszukiwaniach doswiadczonego pomocnika. I rzeczywiscie, twoja reputacja w rozwiazywaniu pewnych {problemow} wyroznia cie sposrod tlumu.",
	["My problems are, so to say, dire news for the whole world. <sigh> I don't want to confuse you with overly complicated and lengthy stories, so long story {short}.."] = "Moje problemy sa.. ze tak powiem.. mam zle wiesi dla calego swiata. <westchnienie> Nie chce cie mec zbyt skomplikowanymi i dlugimi opowiesciami, wiec mowiac w {skrocie}..",
	["My studies indicate that without all doubt Ferumbras the fiendish is in the process of accumulating nearly godlike powers. We have to stop him.\nTherefore I need you to enter a hellish dimension and acquire the parts of a weapon, the godbreaker, powerful enough to stop him once and for all. Are you willing to help me in this dire mission?"] = "Moje badania wskazuja ponad wszelaka watpliwosci, ze {Ferumbras} - ale ten demoniczny - jest w trakcie gromadzenia boskich mocy. Musimy go powstrzymac.\nDlatego chce, bys wszedl do piekielnego wymiaru i zdobyl czesci {lamacza bogow} - broni wystarczajaco poteznej, by raz na zawsze go zatrzymac. Czy jestes gotow mi pomoc w tej niebezpiecznej misji?",
	["Good!, but I need 30 {demonic essences} to exchange with the demonic messenger for a ticket for you to enter the Abodes of Torments."] = "Dobrze! Ale potrzebuje 30 {demonicznych esencji}, by wymienic je u poslanca na bilet pozwalajacy ci wejsc do Siedziby Meki.",
	["Do you have 30 demonic essences to offer to the demonic messenger?"] = "Czy masz 30 {demonicznych esencji}, ktore mozesz ofiarowac?",
	["Excellent! This will empower possibilty to create a breach is enough to let you pass into that hellish hiding place. ..."] = "Swietnie! To da mozliwosc stworzenia szczeliny wystarczajacej, bys mogl przejsc do tego piekielnego schronienia. ...",
	["You don't have the demonic essences, back here when you get it."] = "Nie masz {demonicznych esencji}. Wroc tutaj, gdy je zdobedziesz.",
	["Ascension is a fascinating topic that dates back to efforts and philosophies of some of the most ancient, and mostly extinct, races which fought in the godwars. ...\nProbably born out of desperation, they extensively researched ways to acquire godhood themselves. ...\nSome of them at least even met with moderate success. But the process is complicated at best, and may vary from race to race or even from one individual to another. ...\nThe theories differ vastly and waxed and waned in popularity over the centuries if not aeons. Even today and in human society there are a number of obscure ascension cults. ...\nSome of them claim that humans are most suitable for ascension because they already own a bit of divinity through Banor's godly spark. Lets see how {ferumbras} does now, shall we?"] = "Przeistoczenie w boga to fascynujacy temat, siegajacy rozwazan najstarszych, w wiekszosci wymarlych ras, ktore walczyly w wojnach bogow. ...\nPrawdopodobnie zrodzony z desperacji, temat ten byl przedmiotem intensywnych badan nad sposobami osiagniecia boskosci. ...\nNiektorym z nich udalo sie to przynajmniej czesciowo. Ale proces ten jest niezwykle skomplikowany i moze roznic sie od rasy do rasy, a nawet od jednostki do jednostki. ...\nTeorie na ten temat bardzo sie roznily i zyskiwaly oraz tracily na popularnosci przez wieki. Nawet dzis, w spolecznosci ludzi, istnieje wiele mrocznych kultow przeistoczenia. ...\nNiektore z nich twierdza, ze ludzie sa najbardziej predysponowani do tego, poniewaz juz posiadaja iskre boskosci Banora. Zobaczmy wiec, jak radzi sobie teraz {Ferumbras}, hm?",
	["To my horror I had to recognise that Ferumbras had already made significant progress, and his final bid for ascension is imminent! ...\nHis power levels are already too high for there to be any hope of stopping him with conventional means. ...\nBut not all is lost yet. During my studies about godhood, I learned that the dark Zathroth himself had created a weapon so powerful that it could actually slay a god. ...\nYet even he deemed this so-called '{godbreaker}' too dangerous, and split it into seven parts. These were at some point entrusted to his powerful minions, known as the Ruthless Seven. ..."] = "Ku mojemu przerazeniu odkrylem, ze {Ferumbras} poczynil juz znaczace postepy, a jego ostateczna proba przeistoczenia jest nieuchronna! ...\nPoziom jego mocy jest juz zbyt wysoki, by mozna bylo miec nadzieje na powstrzymanie go konwencjonalnymi metodami. ...\nAle nie wszystko jeszcze stracone. W trakcie moich badan nad boskoscia dowiedzialem sie, ze sam mroczny {Zathroth} stworzyl bron tak potezna, ze mogla zabic boga. ...\nJednak nawet on uznal ten tak zwany '{lamacz bogow}' za zbyt niebezpieczny i rozdzielil go na siedem czesci. Czesci te powierzyl pewnego razu swoim poteznym slugom, znanym jako {Bezlitosna Siodemka}. ...",
	["For a long time, I thought the godbreaker to be some apocryphal myth. But apparently others had learned about the godbreaker in the aeons past and lusted for its power. ...\nThey had gathered hint after hint - until, ultimately, they were squashed by the Seven or their minions; which only made the leads that hinted at them all the more probable. ...\nWhat Zathroth hoped to accomplish with the creation of such a weapon can only be subject to speculation. Assumedly he already had slain Tibiasula, so the godbreaker might have been even more powerful, more absolute. ...\nHowever, it has to be assumed that in the end the sheer power of his creation scared Zathroth, who had to fear the weapon could one day be used against him. So he disassembled it. ...\nHe kept the parts hidden and guarded, and if the resources can be trusted and my interpretation is right, moved them again and again, never satisfied with a hiding place. In the end he entrusted the parts to the {Ruthless Seven}. ...\nKnowing that they would never, ever allow one of their own to come in possession of all parts. Since then, the parts have been hidden in a {demi-plane} shared by the Seven."] = "Przez dlugi czas uwazalem {lamacza bogow} za apokryficzny mit. Jednak najwyrazniej inni poznali sie jego na jego istnieniu w minionych wiekach i pozadali jego mocy. ...\nZbierali wskazowke po wskazowce - az w koncu zostali zmiazdzeni przez {Siodemke} lub ich slugi, co tylko potwierdzilo prawdopodobienstwo ich istnienia. ...\nCzego {Zathroth} chcial dokonac, tworzac taka bron, pozostaje w sferze domyslow. Przypuszczalnie zabil juz {Tibiasule}, wiec lamacz bogow mogl byc jeszcze potezniejszy, bardziej absolutny. ...\nJednak ostatecznie trzeba zalozyc, ze sama potega tej broni przerazila Zathrotha, ktory obawial sie, ze moze ona kiedys zostac uzyta przeciwko niemu. Dlatego ja rozlozyl. ...\nUkryl i strzegl czesci, a jesli zrodla sa wiarygodne, a moja interpretacja sluszna, przenosil je raz za razem, nigdy nie zadowolony z kryjowki. W koncu powierzyl czesci {Bezlitosnej Siodemce}. ...\nWiedzial bowiem, ze nigdy, przenigdy, nie pozwoliliby, by ktorykolwiek z nich wszedl w posiadanie wszystkich czesci. Od tego czasu czesci sa ukryte w {polwymiarze} wspoldzielonym przez Siodemke.",
	["Given the internal power plays amongst the Seven, they are the ideal keepers for individual parts of an powerful artefact. Not one of them would allow his compatriots to hold such a power, and neither would trust the other."] = "Biorac pod uwage wewnetrzne konflikty i potyczki o wladze wsrod {Siodemki}, sa oni idealnymi straznikami poszczegolnych czesci poteznego artefaktu. Zaden z nich nie pozwolilby towarzyszom posiadac takiej mocy, ani nie zaufalby pozostalym.",
	["It is a place, so to say, not completely of this world. It is separate of, yet strongly connected to, our own world. I would imagine it is quite limited in size and its laws of physics and magic should be roughly the same as ours. ...\nBeing home to a host of demons for a while, I expect it to be a hostile and dangerous environment."] = "To miejsce, ze tak powiem, nie do konca z tego swiata. Jest od niego oddzielone, a jednak silnie z nim zwiazane. Wyobrazam sobie, ze jest raczej ograniczone rozmiarem, a jego prawa fizyki i magii sa zblizone do naszych. ...\nPoniewaz od dawna jest siedziba legionu demonow, spodziewam sie, ze to srodowisko wrogie i niebezpieczne.",
	["Although already powerful in his own right, it is obvious that his ultimate goal seems to be the ascension to godly powers. ...\nHis whole existence seems to be centred on becoming a name that strikes fear into the heart of men and to become a persistent figure in the minds of humanity. ...\nThis gives him a hold in reality and a kind of mould to fill with his power and conscience. It's also obvious that this kind of belief of the people alone won't be enough to empower him sufficiently. ...\nTherefore he has to tap into other, probably even more sinister power sources. I can't tell what these sources are, but my scrying revealed that he has reached massive amounts of power. He has probably been infusing himself since years. ...\nBy now he is apparently reaching the end circle of his ascension and could make his final move any day."] = "Mimo ze sam w sobie jest juz potezny, oczywiste jest, ze jego ostatecznym celem jest {przeistoczenie} w boska istote. ...\nCala jego egzystencja zdaje sie skupiac na tym, by stac sie imieniem budzacym strach w sercach ludzi i trwala postacia w swiadomosci ludzkosci. ...\nDaje mu to zakorzenienie w rzeczywistosci i pewien wzorzec, ktory moze wypelnic swoja moca i swiadomoscia. Jest tez oczywiste, ze sama wiara ludzi nie wystarczy, by wystarczajaco go wzmocnic. ...\nDlatego musi siegac po inne, zapewne jeszcze bardziej zlowrogie zrodla mocy. Nie potrafie powiedziec, jakie one sa, ale moje wizje ujawnily, ze osiagnal ogromne poklady energii. Prawdopodobnie wzmacnial sie nimi od lat. ...\nObecnie najwyrazniej zbliza sie do koncowego kregu swego przeistoczenia i moze wykonac ostateczny ruch w kazdej chwili.",
	["Greetings, dear visitor."] = "Witaj, drogi gosciu.",
	--Questlog
	["Ferumbras Ascension"] = "Przeistoczenie Ferumbrasa",
	["Ferumbras the Ascendant"] = "Boskie plany",
	["Defeat Ruthless Seven minions and transport all Godbreaker parts to Mazarius."] = "Pokonaj slugusow Bezlitosnej Siodemki i przetransportuj wszystkie czesci lamacza bogow do Mazariusa.",
	["Stop Ferumbras from ascending! Ask Mazarius for directions if you are lost."] = "Powstrzymaj Ferumbrasa zanim sie przeistoczy. Zapytaj Mazariusa o pomoc, jesli nie zgubiles.",
	["You succesfully stopped Ferumbras' ascension."] = "Udalo ci sie zapobiec przeistoczeniu Ferumbrasa!",
}
