return {
	["Hello. What brings you here?"] = "Witaj. Co cie do mnie sprowadza?",
	["It was many years ago. One day, in Mirkotown, the Undead King of the Crypt appeared, causing havoc among our residents. The city slowly turned into a ruin until 9:37 PM when one of the houses was blown up using dark magic. In that same house, there was a laundry basket, and inside it, a holy relic - socks with John Paul, which flew and landed in the hands of the Crypt King. At that moment, he howled with a demonic voice, 'ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ' and immediately became paralyzed. Without a second thought, all defenders gathered to seal his soul. On the same day, we locked his soul in the banshee cave. The remains of his body were scattered across the desert to prevent any attempts at reanimation. I thought his spirit would be neutralized in the cave, but as I recently found out, he managed to escape from there. I don't know how strong he is right now, but he will surely try to regenerate. We must ultimately destroy him! It won't be an easy task, and before I entrust it to you, you will need to prove to me that you are worthy of leading this crusade. Return to me when you fulfill all my {conditions}."] = "To bylo wiele lat temu. Pewnego dnia w Mirkotown pojawil sie Nieumarly Krol Krypty, ktory sial spustoszenie wsrod naszych mieszkancow. Miasto powoli zamienialo sie w ruine, az do godziny 21:37, w ktorej jeden z domow zostal wysadzony w powietrze, za pomoca mrocznej magii. W tym samym domu znajdowal sie kosz z bielizna, a w jego srodku swieta relikwia - skarpetki z Janem Pawlem. Pod wplywem sily wybuchu, skarpetki pofrunely i wyladowaly na rece Krola Krypty. W tym samym momencie zawyl on demonicznym glosem Weee”eeez teg” jaaankaaaaaa”. Demon zostal natychmiast sparalizowany. Nie czekajac, wszyscy obroncy wykorzystali okazje i zebrali sie, aby zapieczetowac jego dusze. Tego samego dnia zamknelismy jego dusze w jaskini banshee. Szczatki jego ciala rozrzucone zostaly po pustyni, aby nikt nie mogl podjac proby reanimacji jego zwlok. Myslalem, ze w jaskini jego duch bedzie unieszkodliwiony, ale jak ostatnio sie przekonalem, zdolal stamtad uciec. Nie wiem na ile jest silny w tym momencie, ale z pewnoscia bedzie probowal sie odradzac. Musimy go ostatecznie rozpierdolic! Nie bedzie to latwe zadanie i zanim Ci je powierze, bedziesz musial mi pokazac, ze jestes godzien poprowadzic te krucjate. Wroc do mnie gdy spelnisz wszystkie moje {warunki}.",
	["It's interesting that you know our password. Nevertheless, I have no task for you or anything to interest you with."] = "To ciekawe, ze nasz to haslo. Niemniej nie mam dla ciebie zadnego zadania, ani niczego czym moglbym cie zainteresowac.",
	["Welcome again. Are you ready to accept my {conditions}?"] = "Witaj ponownie. Czy jestes juz gotow, zeby zaakceptowac moje {warunki}?",
	["Allakhazam!!!1. Oh, wait, that's not all. I forgot that you also need to visit the magic circles. Each circle consists of 6 stones in 3 different colors, with a special grid in the middle. Stand on all five grids, and I will be able to bless you. I won't tell you where the circles are because you can ask the owners of magic shops in towns about it. Talk to them, and they will guide you to the circles. Just write 'circle' to them, and they will explain everything to you."] = "Alakazam!!!1. A czekaj, to nie wszystko. Zapomnialem, ze jeszcze musisz odwiedzic magiczne kregi. Kazdy krag sklada sie 6 kamieni w 3 roznych kolorach, ze specjalna kratka na srodku. Stan na wszystkich pieciu kratkach, a bede mogl cie poblogoslawic. Nie bede Ci mowil gdzie sa okregi, bo mozesz zapytac o to wlascicieli magic shopow w miastach. Porozmawiaj z nimi, a poprowadza cie do kregow. Wystarczy ze napiszesz do nich 'krag' i Ci wszystko wytlumacza.",
	["My conditions are to complete the following tasks: Druid Path, Yalahar Quest. While you know the secret password, I also want other druids and elves to vouch for you. Additionally, you must visit at least one poi throne. If you are ready, ask me again about {conditions}."] = "Moje warunki to wykonanie nastepujacych zadan: Sciezka druida, Yalahar Quest. Co prawda znasz tajemne haslo, ale chce, zeby inni druidzi i elfowie zaswiadczyli za ciebie. Dodatkowo musisz odwiedzic co najmniej jeden tron poi. Jezeli jestes gotowy, to zapytaj mnie ponownie o {warunki}.",
	["Hocus Pocus! Now everything should work. Something very dark lurks in the pyramid's underground. Ask Konmuld for advice, and maybe you will escape from there alive. Oh, I almost forgot: from now on, you can now use the sealed doors in the pyramid."] = "Hokus Pokus! Teraz juz wszystko powinno grac. W podziemiach piramidy czai sie cos bardzo mrocznego. Zapytaj Konmulda o porade, a byc moze ujdziesz stamtad z zyciem. Bym zapomnial: od teraz mozesz uzywac zapieczetowanych drzwi w piramidzie.",
	["Ask the individual owners of magic shops about the locations of the circles."] = "Zapytaj poszczegolnych wlascicieli magic shopow o lokacje kregow.",
	["Here is your reward for your effort. Wait, wait... where is my backpack!? It was probably Chester doing. Well, I guess your bonus reward is gone."] = "Prosze, oto nagroda za twoj wysilek. Chwila, chwila... gdzie jest moj plecak!? To pewnie ten rzezimieszek Czeslaw. No coz, chyba przepadl bonus.",
	["You step on circle number "] = "Stanales na kregu nr. ",
	["To fulfill Gandalf's ordeal, you need to stand on "] = "Aby wypelnic zadanie Gandalfa, musisz stanac jeszcze na ",
	[" remaining circles."] = " pozostalych kregach.",
	["If you really know what danger he is, deal with his ally first - Sultan of Phantasms. Also deal with that swindler, Chester, who tried to fuck me over in Down's Labyrinth."] = "Jesli zdajesz sobie sprawe jak bardzo niebiezpieczny jest to typek, to zajmij sie najpierw jego pomagierem - Sultanem Phatasmow. I jeszcze zajmij sie Czeslawem Kransoludem, ktory probowal mnie wydymac podczas mojej pierwszej wyprawy do labiryntu Downa.",
	["Gandalf sent you here, right? If you want to go to the down pyramid, you need to know that there is an Undead Crypt King waiting, and that {encounter} him will not be easy by any means. To summon him, you will need a few ingredients. Take the most necessary things: wood, cauldron, vial and lighter. For the ritual you will need {bones} so foul that they lower the wavelength of the light around. Plus the {signet ring} of an undead lord, and a {cloak} made of the skin of unbaptized children. If you're going to collect these items, ask me about the {ritual}."] = "Przyslal cie Gandalf, tak? Jesli chcesz udac sie do piramidy downa, to musisz wiedziec, ze na jej koncu czeka Nieumarly Krol krypty, oraz, ze {walka} z nim nie bedzie w zadnym wypadku latwa. Aby go przywolac, bedziesz potrzebowac kilku skladnikow. Zabierz ze soba najpotrzebniejsze rzeczy: drewno, kociol, fiolke oraz zapalniczke. Do rytualu bedziesz potrzebowac {kosci} tak plugawych, ze obnizaja dlugosc fal swiatla wokol. Do tego {sygnet} nieumarlego lorda, i {plaszcz} ze skory nieochrzczonych dzieci. Jesli zamierzasz zebrac te przedmioty, to spytaj mnie o {rytual}.",
	["The Crypt King is skilled in many areas, not just magic. In addition to the standard set of spells of a generic villain, such as summoning the undead and shooting lasers, he can use spells from other universes. Apparently his mother had allowed him to play WoW when he was little, and now he has mastered some of the skills available there. He studied the 'sciences' of goblins, so he can quickly construct bombs. If I remember correctly, you'll probably have to cover the bombs with your body so they don't blow up the entire platform. The last thing you need to know is that the Vault King is constantly increasing his damage, so he is unwilling to change his current target."] = 'Krol Krypty posiadl umiejetnosci z wielu dziedzin, nie tylko magii. Oprocz standardowego zestawu czarow generycznego zlodupca, takich jak przywolywanie nieumarlych i strzelanie z laserkow, potrafi on uzywac czarow z innych uniwersum. Widocznie matka nie zabraniala mu grac w WoWa jak byl maly, i teraz opanowal niektore z dostepych tam umiejetnosci. Studiowal on "nauki" goblinow, wiec potrafi napredce konstruowac bomby. Jesli dobrze kojarze, to pewnie bedziecie musieli zaslaniac te bomby swoim cialem, zeby nie wysadzily calej platformy. Ostatnia rzecz, o ktorej musisz wiedziec, to fakt, ze Krol Krypty nieustannie zwieksza zadawane przez siebie obrazenia, w zwiazku z tym niechetnie zmienia swoj aktualny cel.',
	["It's called Unholy Bone."] = "Na zachodzie mowia na nie Unholy Bone.",
	["This ring has vanished somewhere, maybe {Grave Digger} will tell you more about it."] = "Pierscien ten przepadl gdzies, nie wiadomo gdzie. Mozliwe, ze {Grave Digger} powie ci cos wiecej o sygnecie.",
	["He sells equipment in Mirko, I think you know him."] = "Sprzedaje lopaty w Mirko, pewnie go kojarzysz.",
	["Only the one group could create such a thing - PiS cultists from Sybir."] = "Tylko jedna grupa zawodowa mogla sie dopuscic stworzenia czegos takiego - kultysci PiS z Sybiru.",
	["Before you start, you must summon three guards whose skeletons are blocking access to the ritual site. You'll probably have to defeat them to get further. To summon each of them, you will show perseverance to people unknown to this world. This will require you to have fourteen different {effects}. Somewhere in the depths of the dungeons you will find a circle made of stones. It is where the ritual of summoning the Crypt King will take place."] = "Przed rozpoczeciem musisz wywolac trzech straznikow, ktorych szkielety blokuja dostep do miejsca rytualu. Prawdopodobnie bedziesz zmuszony ich pokonac, zeby dostac sie dalej. Aby przywolac kazdego z nich, wykazesz sie wytrwaloscia nieznanom ludziom tego swiata. Bedzie to od ciebie wymagalo posiadania czternastu roznych {efektow}. Gdzies w glebi lochow znajdziesz krag ulozony z kamieni. To wlasnie na nim odbedzie sie rytual przywolania Krola Krypty.",
	["I managed to extract this knowledge from the ancient collections in the library of the Lvivversity of Archmages. If you think you can read these notes - I hid the scroll under the bush to the right. And remember, not all of the effects listed there are real - apparently this document was written on the knee."] = "Te wiedze zdolalem wydobyc z pradawnych zbiorow w bibliotece Lubuskiej Uczelni Arcymagow. Jezeli uwazasz, ze zdolasz odczytac te zapiski - zwoj schowalem pod krzakiem obok. Aha, nie wszystkie z wymienionych tam efektow sa prawdziwe - widocznie dokument ten spisywano na kolanie.",
	["I don't know how you know about this ring, but if you want to find it, listen. It was in the Diremaw caves under the cultist swamp. As I approached the Fire Fucker's cave, he roared so hard that I shit myself and started running away as fast as I could. In this haste, one of the dummy atifacts I used for... never mind, fell out of my backpack. Inside the dummy I had dropped there was a ring. If I remember correctly, this dummy was supposed to imitate a precious miniature of the ship. Coming back to how I escaped, all I remember is waking up in the temple. If you want, you can look for that ring, I don't need it anymore."] = "Nie wiem, skad wiesz o istnieniu tego sygnetu, ale jezeli chcesz go odnalezc, to sluchaj. Bylo to w jaskiniach Diremawow pod bagnem kultystow. Gdy zblizalem sie do jaskini Ognistego Skurwiwija, ten ryknal tak, ze obsralem sie i zaczalem jak najszybciej stamtad uciekac. Z tego pospiechu wypadla mi z plecaka jedna z atrap atefaktow, ktorych uzywalem do.. a z reszta, niewazne. W srodku tej atrapy, ktora mi wypadla, ukryty byl pierscien. Jezeli dobrze pamietam, to atrapa ta miala imitowac drogocenna miniaturke statku. Wracajac do tego jak ucieklem, pamietam tylko jak obudzilem sie w temple. Jesli chcesz, to mozesz poszukac tego pierscienia, mi on juz sie nie przyda.",
	-- Path of the Undead
	["Path of the Undead"] = "Sciezka Nieumarlych",
	["Test of Strength"] = "Proba sily",
	["Gandalf told you about the history of Mirkotown. Now, ask him what conditions you need to fulfill to get his help."] = "Gandalf opowiedzial Ci dawne dzieje Mirkotown. Zapytaj go teraz jakie warunki musisz spelnic, zeby uzyskac jego pomoc.",
	["Gandalf promised to bless your cause, but first, you must visit special magical circles."] = "Gandalf obiecal poblogoslawic twoja sprawe, ale najpierw musisz odwiedzic specjalne, magiczne kregi.",
	["Endurance Test"] = "Proba wytrzymalosci",
	["Gandalf has blessed you and advised you to go to Konmuld for further instructions."] = "Gandalf cie poblogoslawil oraz poradzil udac sie do Konmulda po dalsze instrukcje.",
	["The Final Battle"] = "Ostateczne starcie",
	["Gather the necessary items, summon, and ultimately defeat the Undead Crypt King."] = "Zbierz potrzebne przedmioty, przywolaj i ostatecznie pokonaj Nieumarlego Krola Krypty.",
	["You have defeated the Undead Crypt King. Return to Gandalf for your reward."] = "Pokonales Nieumarlego Krola Krypty. Wroc do Gandalfa po nagrode.",
	["Gandalf misplaced a certain item intended as a reward, but you have received his other gifts."] = "Gandalf zgubil pewien przedmiot, ktory przeznaczyl na nagrode, ale otrzymales od niego pozostale podarunki.",
	["King of Rats Headquarters Status"] = function(context)
		local result = -1
		for _, storage in pairs(Storage.KingOfRatsHQ.Portals) do
			local value = context.player:getStorageValue(storage)
			if value == 1 then
				result = result + 1
			end
		end
		return string.format("Aktualnie udalo ci sie zebrac %d artefaktow.", result)
	end,
}
