dofile(DATA_DIRECTORY .. "/lib/core/storages.lua")
dofile(DATA_DIRECTORY .. "/lib/core/quest_state.lua")
dofile(DATA_DIRECTORY .. "/lib/core/task_data.lua")
dofile(DATA_DIRECTORY .. "/lib/core/daily_task_data.lua")
dofile(DATA_DIRECTORY .. "/lib/core/task_lib.lua")
