NEXT_QUEST_ID = NEXT_QUEST_ID or 0
function NextQuestId()
	NEXT_QUEST_ID = NEXT_QUEST_ID + 1
	return NEXT_QUEST_ID
end

NEXT_MISSION_ID = NEXT_MISSION_ID or 0
function NextMissionId()
	NEXT_MISSION_ID = NEXT_MISSION_ID + 1
	return NEXT_MISSION_ID
end

TASKS_QUEST_STORAGE = NextQuestId()
DAILY_TASK_STORAGE = NextQuestId()

if not Quests then
	Quests = {
		[TASKS_QUEST_STORAGE] = {
			name = "Tasks",
			startStorageId = Storage.Tasks.TaskInfo,
			startStorageValue = 0,
			missions = {
				[1] = {
					name = "Task informations",
					storageId = Storage.Tasks.TaskInfo,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 1,
					description = "TASKS_HELP_WINDOW_INFO",
				},
			},
		},
		[DAILY_TASK_STORAGE] = {
			name = "Daily task",
			startStorageId = Storage.DailyTasks.DailyTaskInfo,
			startStorageValue = 0,
			missions = {
				[1] = {
					name = "Daily tasks information",
					storageId = Storage.DailyTasks.DailyTaskInfo,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 1,
					description = "DAILY_TASKS_HELP_WINDOW_INFO",
				},
			},
		},
		[NextQuestId()] = {
			name = "Arena",
			startStorageId = 300,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "First arena",
					storageId = 301,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "Kill:\nFrostfur\nBloodpaw\nBovinus\nAchad\nColerian the Barbarian\nThe Hairy One\nAxeitus Headbanger\nRocky\nCursed Gladiator\nOrcus the Cruel",
				},
				[2] = {
					name = "Second arena",
					storageId = 302,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "Kill:\nAvalanche\nKreebosh the Exile\nThe Dark Dancer\nThe Hag\nSlim\nGrimgor Guteater\nDrasilla\nSpirit of Earth\nSpirit of Water\nSpirit of Fire",
				},
				[3] = {
					name = "Third arena",
					storageId = 303,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "Kill:\nWebster\nDarakan the Executioner\nNorgle Glacierbeard\nThe Pit Lord\nSvoren the Mad\nThe Masked Marauder\nGnorre Chyllson\nFallen Mooh'Tah Master Ghar\nDeathbringer\nThe Obliverator",
				},
				[4] = {
					name = "Fourth arena",
					storageId = 304,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "Arena, extreme level.",
				},
			},
		},
		[NextQuestId()] = {
			name = "Firestarter",
			startStorageId = 11009,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Mission 1: Fiery Beginnings",
					storageId = 11009,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Hymel asked you to burn down the herbs he left on his house on north side of MikroTown.",
						[2] = "You burnt the herbs, now talk again with Hymel.",
						[3] = "Hymel gave you an incendiary firebug. From now on you can buy more firebugs from him.",
					},
				},
				[2] = {
					name = "Mission 2: Little Treat",
					storageId = 11010,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Hymel want to mischief the local guards, by setting an old tree on fire. You can find it near their resting camp.",
						[2] = "You did it, the guards didn't even notice, go back and see Hymel.",
						[3] = "In return for your help, Hymel gave you the staff of a real reefer.",
					},
				},
				[3] = {
					name = "Mission 3: How High",
					storageId = 11011,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Hymel told you about how he and his mates once sowed 5 mysterious herbs all around MirkoTown. Unfortunately he doesn't remember where exactly they did sow them. They look like usual red flowers. Find them and set them ablaze with firebug.",
						[2] = "The smell of weed is now around the whole city, you managed to burn all the flowers.",
						[3] = "Hymel made you a true pyromaniac and gave you his arsonist weapon.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "The Way of a Druid",
			startStorageId = 11007,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "The Council of Druids",
					storageId = 11007,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 7,
					states = {
						[1] = "You met one of the druids, if you helped him, he would tell you about the Council.",
						[2] = "You helped the first druid. This is the beginning of your journey to become one of them. Find the remaining druid, and provide them with your help.",
						[3] = "The Mother Nature is watching, and she is cherishing as you helped two of the druids.",
						[4] = "Your efforts induced The Mother Nature let you gather water from well at the great tree.",
						[5] = "You drew water from well at the sacred tree. Now try to find the next druid.",
						[6] = "Your kindness goes a long way, you helped four druids so far.",
						[7] = "You helped all the druids, and you have been introduced to their Council. Now you can harvest a blossom of the Griffinclaw plant, which grows inside a great tree.",
					},
				},
				[2] = {
					name = "Deer Season",
					storageId = 11008,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Radaghast asked you to burn down the hunters' stock of wood. This should prove to help a lot of animals to survive during the hunting season.",
						[2] = "You managed to burn down the stock of wood in the hunters' village. Make haste and tell about this to Radaghast.",
						[3] = "Radaghast handed you a slingshot for your help, also he erranded you to help other druids from the council he told you about.",
					},
				},
				[3] = {
					name = "Taken: Benek",
					storageId = 11017,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Estep is Wailing since orcs taken his Wolf companion.",
						[2] = "The wolf has been freed, deliver a good message to Estep.",
						[3] = "Estep handed over this knife in his gratitude.",
					},
				},
				[4] = {
					name = "Rude eviction",
					storageId = 11061,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "SandNigger asked you to help him reclaim his secret spell.",
						[2] = "You managed to find and combust the spell, come back to Sandnigger.",
						[3] = "For your kind deed, you have been granted The Lion Amulet.",
					},
				},
				[5] = {
					name = "The secret ingredient",
					storageId = 11067,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Mundral asked you to get the medicine for his sick pet. You can ask Ornuld for it.",
						[2] = "Turn out that Mundral belongs to the Druid Council. He put in a good word to his druid friends and he gifted you with bamboo leaves.",
					},
				},
				[6] = {
					name = "The Ornuld's medicine",
					storageId = 11068,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Ornuld wishes to have a one wyrm egg. If you manage to do this favor, he will reward you with the medicine.",
						[2] = "You found the wyrm's egg, hand it to Ornuld.",
						[3] = "Ornuld gave you the medicine in exchange for the wyrm's egg.",
					},
				},
				[7] = {
					name = "The Singing Crystal",
					storageId = 11069,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Malfurion is in need of an ice crystal fragment for his experiment.",
						[2] = "You managed to gather a bunch of crystal, go back to Malfurion.",
						[3] = "For your help, Malfurion gave you a gift.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Ariel's Friend",
			startStorageId = 11000,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Helping the Ariel",
					storageId = 11000,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Ariel asked you to bring him his friend's favorite flower. Namely it is the Heaven Blossom. Some elves keep it in their pouch.",
						[2] = "Ariel asked you to pay respect to his friend by laying these flowers on his grave. It is located on a nearby hill. If you do that, he will tell you his story.",
						[3] = "You put the flowers on Ariel's friend's grave, now come back to Ariel.",
						[4] = "Ariel endowed you with a bow and a few minor gifts. He is now ready to tell you his story, whenever you ask him to do so.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Yalahari Quest",
			startStorageId = 11002,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Mission 1: Love is in the air",
					storageId = 11002,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 9,
					states = {
						[1] = "Ariel asked you to hand over a party invitation to Madame Malkin.",
						[2] = "Madame refused Ariel's request to go out with him. Tell him this bad news.",
						[3] = "Perhaps Ariel's friend, Old Postman, knows a way to influence Madame Malkin.",
						[4] = "Old Postman had a disgraceful idea to steal an elixir of love. He told you to fill this vial he gave you. You can probably find supplies of love elixir at Alchemists' quarters, north of MirkoTown.",
						[5] = "Success! You filled the vial with an elixir. Go back to the postman and ask him for further directions.",
						[6] = "Old Postman mentioned that in order for the elixir to properly work, you need to dilute Ariel's string of hair in it. After you do this, bring the elixir to Madame Malkin.",
						[8] = "Turns out that the “wine” worked as intended. Tell Ariel about it.",
						[9] = "Ariel rejoices to know about Madame's feelings. He also revealed the secret Yalaharian greeting to you: Aloha. You can visit Gertrdue or Konmuld now.",
					},
				},
				[2] = {
					name = "Mission 2: A morbid Liquor",
					storageId = 11044,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Find an immensely strong vodka in the lizard headquarters, and bring it to Gertruda.",
						[2] = "In exchange for your help with finding the beverage, Gertruda is willing to help you with preparing concoctions and special rodenticides.",
						[3] = "After treating Konmuld with vodka, he agreed to talk with you.",
					},
				},
				[3] = {
					name = "Mission 3: Prelude to Thaumaturgy",
					storageId = 11047,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 5,
					states = {
						[1] = "Konmuld asked you to bring him a virgin's soul. You can ask Grave Digger for help with your mission.",
						[2] = "Grave Digger said that there are no remaining virgins left, however, you can dig up a virgin's soul from a grave.",
						[3] = "You managed to get a virgin's soul. Now go see Konmuld.",
						[4] = "Konmuld offered you to choose one of the Yalahari set pieces to keep for yourself.",
						[5] = "In his gratitude, Konmuld gave you one of his old Yalahari set pieces.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "The First Steps",
			startStorageId = 11019,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Research",
					storageId = 11019,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 12,
					states = {
						[1] = "Find Commissioner Fisher and ask for a mission.",
						[2] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 0/10.",
						[3] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 1/10.",
						[4] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 2/10.",
						[5] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 3/10.",
						[6] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 4/10.",
						[7] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 5/10.",
						[8] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 6/10.",
						[9] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 7/10.",
						[10] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 8/10.",
						[11] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 9/10.",
						[12] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 10/10.",
					},
				},
				[2] = {
					name = "Wood Delivery",
					storageId = 11030,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 6,
					states = {
						[1] = "Go to Knurowo's port and find out what happened to the wood delivery.",
						[2] = "Woody is sure that the wood was shipped on a caravan leaving Knurowo. He asked you to investigate this.",
						[3] = "Tell Ryba that Waski and his mafia stole all of the wood delivery.",
						[4] = "Commissioner Fisher ordered you to recover the stolen wood, but he also warned you about the Waski's mafia.",
						[5] = "Waski gave up, and he is going to let Officer Ryba take the wood back. Report back to Ryba.",
						[6] = "Your merits earned you a special reward. Officer Ryba sent you to Trollsky, where you can receive your reward.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "To Carry the Pigs",
			startStorageId = 11034,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "To be like the Schwarzenegger",
					storageId = 11033,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Collect these items for me: 5 orc tooth, 5 carrion worm fangs, and 1 vampire teeth.",
						[2] = "Arni glanced at these teeth, and asked you to find someone who can make them into necklace.",
						[3] = "Madame Malkin gladly made this necklace for Arni.",
						[4] = "In exchange for the teeth necklace, Arni gave u his old armour and a ring.",
					},
				},
				[2] = {
					name = "Half turn Kick",
					storageId = 11035,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Cordell Walker is suspecting bandits of commissioning illegal transactions in their encampment.",
						[2] = "He was right. Now go to the Price Kebab and ask Shivganesh for translation.",
						[3] = "It wasn't hard at all for Shivganesh. Take the list and translation back to Cordell Walker.",
						[4] = "You have received MirkoTown guard hat for your help.",
					},
				},
				[3] = {
					name = "A Balanced Diet",
					storageId = 11037,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Collect 1 slimming carrot for fat Mirek.",
						[2] = "The carrot was dogshit, and u received chocolate slush in for your effort.",
					},
				},
				[4] = {
					name = "Kitz's Dominando",
					storageId = 11039,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Arrange a special bow from elf adobe.",
						[2] = "You have received the item from Legolas. Go give it to Kitz.",
						[3] = "Turns out elvish bow sucks. Kitz now wishes to rook the elves. In return for your efforts you received his old bow.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Ocellatus Xddd",
			startStorageId = 11041,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Tickets",
					storageId = 11041,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 5,
					states = {
						[1] = "Recover the match tickets whose have been stolen from Ocellatus.",
						[2] = "You found the Tickets in a bandits tent.",
						[3] = "You gave tickets back to Ocellatus.",
						[4] = "Ocellatus asks you to bring him specific food. Ask Pewter for help.",
						[5] = "U brang food to Ocellatus. In his gratitude, he gave you outfit and let you sail his boat.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Demon Oak",
			startStorageId = 1013,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Demon Oak",
					storageId = 1013,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "You have made your way into the den of Demon Oak. Try to find someone who will tell you more about it.",
						[2] = "Oldrak gave you information regarding Demon Oak. He can bless an axe if you bring him one. The blessed axe should help you fight the Oak.",
						[3] = "You defeated the Demon Oak! Report to Oldrak.",
						[4] = "You reported to Oldrak about your victory. You have been rewarded for your efforts: Oldrak told you a secret about the way to the Elvish treasury.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Local Support",
			startStorageId = Storage.TrudnePoczatki.Rozeznanie,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Freaking Rats",
					storageId = Storage.PomocMiejscowym.PrzekleteSzczury,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Walmart wishes she knew how to repel rats. Find out where Gertruda lives. She should know how to craft a rat poison.",
						[2] = "Gertruda asked you to bring her one mouldy cheese.",
						[3] = "Cheese is now poisonous. Bring it to Walmart, so she can repel the rats.",
						[4] = "Walmart didn't have time to make use of the poisonous cheese, but she already gave you your reward: Carrot cake and a minor gift.",
					},
				},
				[2] = {
					name = "Cheap Recycling",
					storageId = Storage.PomocMiejscowym.TaniRecykling,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Malkin asked you to bring her 1 piece of cloth of every color.",
						[2] = "Madame Malkin is grateful for your effort, and since now you can exchange mystic turbans, red robe, and green tunic for corresponding pieces of cloth.",
					},
				},
				[3] = {
					name = "Broken Orb",
					storageId = Storage.PomocMiejscowym.ZniszczonaKula,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Gypsy needs a new Crystal ball. Bring it to him, and he will reward you abundantly.",
						[2] = "The crystal ball wasn't perfect, but Gypsy is fine with it. Since now he will also let you exchange red gem to ring of healing.",
					},
				},
				[4] = {
					name = "Biodegradable",
					storageId = Storage.Biodegradowalny.Questline,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Old postman asked you to find a package. You know that this cargo was supposed to arrive by water from the west.",
						[2] = "You found the package for Old Postman. Return to him and give it to him.",
						[3] = "You received a reward from Old Postman in exchange for helping locate the overdue shipment. He mentioned that you can also deliver Zanet's Box to Old Anon.",
						[4] = "You took the box from Old Postman, which you should deliver to Old Anon.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "The Silence of the Lambs",
			startStorageId = 11065,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "The test of Strength",
					storageId = 11065,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Lecter asked you for 5 vampire teeth.",
						[2] = "In exchange for your help, Lecter bestowed you with his old soul-extraction tool.",
					},
				},
				[2] = {
					name = "Fashionista clothes",
					storageId = 11066,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Lecter asked you to bring him 20 leathers of every kind.",
						[2] = "For your help you have been taught how to skin human carcass.",
					},
				},
				[3] = {
					name = "Lecter's recipe",
					storageId = 11073,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Lecter wants you to hoard 15 human hearts and 20 human livers. He needs them for his cannibals party.",
						[2] = "In exchange for this favor you have been introduced to the cannibal club. You also received their outfits.",
					},
				},
				[4] = {
					name = "Hearts collected",
					storageId = 11074,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 15,
					description = "Hearts collected",
				},
				[5] = {
					name = "Livers collected",
					storageId = 11075,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 20,
					description = "Livers collected Status",
				},
			},
		},
		[NextQuestId()] = {
			name = "Unwanted Guests",
			startStorageId = 11076,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Damned Barbarians",
					storageId = 11076,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "Bring Brutetamers Staff and Fur Boots to Dziadek Mroz.",
				},
			},
		},
		[NextQuestId()] = {
			name = "The Inquisition",
			startStorageId = 12160,
			startStorageValue = 2,
			missions = {
				[1] = {
					name = "Mission 1: Interrogation",
					storageId = 12161,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 7,
					description = "Your mission is to investigate the 5 guards regarding the Heretic behavior. Tim, Kulag, Grof, Miles and Walter are their names. If you do well you see a holy sprite on you.",
					states = {
						[1] = "You investigated 1 of 5 guards.",
						[2] = "You investigated 2 of 5 guards.",
						[3] = "You investigated 3 of 5 guards.",
						[4] = "You investigated 4 of 5 guards.",
						[5] = "You investigated 5 of 5 guards. Get back to Sybir and report your mission to Henricus.",
						[6] = "You investigated all guards.",
					},
				},
				[2] = {
					name = "Mission 2: Eclipse",
					storageId = 12162,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					description = "Henricus tells you to get The Witches' Grimoire, he sends you to Mirko Town where you can find to the witches' swamps. Use the vial of holy water that he gives you on the big cauldron and open the chest hidden in some witch hut, then bring the witches' grimoire to Henricus.",
					states = {
						[1] = "Find The Witches' Grimoire and bring it to Henricus.",
						[2] = "You already brought The Witches' Grimoire to Henricus.",
					},
				},
				[3] = {
					name = "Mission 3: Vampire Hunt",
					storageId = 12163,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 6,
					description = "Henricus wants you to find the Dwarfish Vampire Hunter, Storkus, located deep in dwarven mines. It's a good idea to bring your 20 Vampire Dusts with you to save some time.",
					states = {
						[1] = "Go back to Storkus and ask for a mission.",
						[2] = "Now Storkus wants you to kill a vampire lord, The Count. The Count is located deep under the forgotten cemetery near the hunter camp. To summon The Count, you must use the coffin in the center of the room. Kill him and bring The Ring of the Count to Storkus.",
						[3] = "Kill The Count and bring his ring to Storkus, and then ask for a mission.",
						[4] = "Return to Henricus and tell him that you've finished your job here.",
						[5] = "Get back to Sybir and report your mission to Henricus.",
					},
				},
				[4] = {
					name = "Mission 4: The Haunted Ruin",
					storageId = 12164,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					description = "Henricus will give you a Special Flask (vial of holy water). You can find some abandoned pirate ruins near hero village in the jungle. Use this vial of holy water on some spot in the haunted ruin to drive out the evil being.",
					states = {
						[1] = "Kill the Pirate Ghost and get back to Sybir and report your mission to Henricus.",
						[2] = "You already cleaned the abandoned and haunted place, ask Henricus for a new mission.",
					},
				},
				[5] = {
					name = "Mission 5: Essential Gathering",
					storageId = 12165,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					description = "Henricus wants 20 Demonic Essences as proof of your accomplishments.",
					states = {
						[1] = "Now ask Henricus for an outfit to get the Demon Hunter Outfit.",
						[2] = "You got the Demon Hunter Outfit! Ask Henricus for a mission to unlock more addons.",
					},
				},
				[6] = {
					name = "Mission 6: The Demon Ungreez",
					storageId = 12166,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					description = "Henricus wants you to kill a demon called Ungreez. Head to the desert demon lair and go down a few levels.",
					states = {
						[1] = "You killed Ungreez, report your mission to Henricus.",
						[2] = "You got the first addon of Demon Hunter Outfit! Ask Henricus for a mission to unlock more addons.",
					},
				},
				[7] = {
					name = "Mission 7: The Shadow Nexus",
					storageId = 12167,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 5,
					description = "Your mission is to go to the Demon Forge and slay seven of The Ruthless Seven Minions. The Demon Forge is located in the Sybir, somewhere in hidden cultist ruins.",
					states = {
						[1] = "You destroyed the shadow nexus! Get back to Henricus and report your mission.",
						[2] = "Now ask Henricus for an outfit. He will give you the 2nd addon of the Demon Hunter Outfits.",
						[3] = "You got the second addon of Demon Hunter Outfit! Go now to the reward room and choose one wisely!",
						[4] = "You have completed The Inquisition Quest!",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Bigfoot's Burden",
			startStorageId = 900,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Reputation points",
					storageId = 921,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 1000,
					description = "Current reputation points",
				},
				[2] = {
					name = "Daily Minor: Crystal Keeper",
					storageId = 932,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					description = "Daily Minor: Crystal Keeper Status",
				},
				[3] = {
					name = "Daily Minor: Raiders of the lost Spark",
					storageId = 934,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 7,
					description = "Daily Minor: Raiders of the lost Spark Status",
				},
				[4] = {
					name = "Daily Minor Plus: Exterminators",
					storageId = 937,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 10,
					description = "Daily Minor Plus: Exterminators Status",
				},
				[5] = {
					name = "Daily Minor Plus: Mushroom Digger",
					storageId = 940,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					description = "Daily Minor Plus: Mushroom Digger Status",
				},
				[6] = {
					name = "Daily Major Advanced: Spores",
					storageId = 948,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					description = "Gather spores in the correct order. Your spore gathering list will display the next color you have to look for.",
				},
				[7] = {
					name = "Daily Major Advanced: Yet Another Grinding",
					storageId = 952,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 1,
					description = "Gather a grindstone from the lava area and report back.",
				},
				[8] = {
					name = "Daily Major: Matchmaker",
					storageId = 943,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "You have to enter the crystal caves and find a crystal that is fitting the crystal you got from the gnomes. Use the crystal on one of the bigger red crystal in the caves to bond them.",
				},
				[9] = {
					name = "Daily Major: The Tinker's Bell",
					storageId = 946,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					description = "Daily Major: The Tinker's Bell Status",
				},
			},
		},
		[NextQuestId()] = {
			name = "The Ape City",
			startStorageId = 11101,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Hairycles Missions",
					storageId = 11102,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 18,
					states = {
						[1] = "Find whisper moss in the dworc settlement and bring it back to Hairycles.",
						[2] = "You have completed the first mission. Hairycles was happy about the whisper moss you gave to him. He might have another mission for you.",
						[3] = "Hairycles asked you to bring him cough syrup from a human settlement. A healer might know more about this medicine.",
						[4] = "You have completed the second mission. Hairycles was happy about the cough syrup you gave to him. He might have another mission for you.",
						[5] = "Hairycles asked you to bring him a magical scroll from the lizard settlement.",
						[6] = "You have completed the third mission. Hairycles appreciated that you brought the scroll to him and will try to read it. Maybe he has another mission for you later.",
						[7] = "Since Hairycles was not able to read the scroll you brought him, he asked you to visit a tomb northwest from Hurghada. Proceed in this tomb until you find an obelisk between red stones and read it.",
						[8] = "You have completed the fourth mission. Hairycles read your mind and can now translate the lizard scroll. He might have another mission for you.",
						[9] = "Hairycles wants to create a life charm for the ape people. He needs a hydra egg since it has strong regenerating powers.",
						[10] = "You have completed the fifth mission. Hairycles attempts to create a might charm for the protection of the ape people. He might have another mission for you later.",
						[11] = "Hairycles need a witches' cap mushroom which is supposed to grow on swamp inhabited by Beholders.",
						[12] = "You have completed the sixth mission. You brought the witches' cap mushroom back to Hairycles. He might have another mission for you.",
						[13] = "Hairycles read that the Lizards are planning to summon the Demon Lizards to help regain their former temple. Perhaps the premature lighting of their firecamp will thwart their plans.",
						[14] = "You have completed the seventh mission. You found a way to prevent the Lizards from opening the hellish gates. Hairycles might have another mission for you.",
						[15] = "The apes now need a symbol of their faith. Find a hair of the giant, holy ape and bring it back. It may be located in caves inhabited by Behemoths.",
						[16] = "You completed the eighth mission. Hairycles gladly accepted the hair of the ape god which you brought him. He told you to have one final mission for you.",
						[17] = "Go into the deepest catacombs under Banuta and destroy the monument of the snake god with the hammer that Hairycles gave to you.",
						[18] = "You successfully destroyed the monument of the snake god. As reward, you can buy sacred statues from Hairycles. If you haven't done so yet, you should also ask him for a shaman outfit.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Top Chef",
			startStorageId = Storage.TopChef.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Top Chef",
					storageId = Storage.TopChef.Questline,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 16,
					description = "TOP_CHEF_MISSION_DESCRIPTION",
				},
			},
		},
		[NextQuestId()] = {
			name = "The Dream Courts",
			startStorageId = 12200,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "The Dream Courts",
					storageId = 12200,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 5,
					description = "Find and talk to Vanys in order to help him. He stays in Summer Court in the huge forest located far south from Mirko Town.",
					states = {
						[1] = "Vanys gave you a dream talisman that you'll need to empower eight ward stones located around the world. Ward stone locations you were told about are: mountains of Pirate Island, bonebast coast in the desert, water elemental cave beneath Kongo, depths of Seacrest Serpent lair, west coast of Sybir and Barbarian camp, Nightmare Island, Buried Cathedral beneath Karaiby.",
						[2] = "Vanys let you enter the dream labyrinth. Find a way to enter the Nightmare Beast's lair and defeat him. Elven Parchment from Vanys chest may help you.",
						[3] = "You have defeated The Nightmare Beast. Talk about this to Vanys.",
						[4] = "Vanys gifted you with a traditional dream warrior outfit.",
					},
				},
				[2] = {
					name = "Helping of Stricken Soul",
					storageId = 12232,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					description = "Restore connection and open this nexus to access the buried cathedral. You need to find a way to pass the entrance in the cellar.",
					states = {
						[1] = "You successfully passed the cellar entrance. Find a way to restore the portal to the buried cathedral.",
						[2] = "You restored a portal and successfully entered the buried cathedral. Try to find and defeat the Faceless Bane. You'll need to gain some knowledge in order to enter her nest. Maybe there are some documents around...",
						[3] = "You successfully defeated the Faceless Bane.",
					},
				},
				[3] = {
					name = "Empowered Wardstones",
					storageId = 12209,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 8,
					description = "Empowered Wardstones",
				},
				[4] = {
					name = "Readed documents",
					storageId = 12214,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					description = "Readed documents",
				},
			},
		},
		[NextQuestId()] = {
			name = "Liquid Black",
			startStorageId = 24001,
			startStorageValue = 2,
			missions = {
				[1] = {
					name = "Visitor",
					storageId = 24001,
					missionId = NextMissionId(),
					startValue = 2,
					endValue = 5,
					states = {
						[2] = "You have found notes and coordinates. Try to find out what they are for.",
						[3] = "You got teleported to Mezamir by a strange teleporter. Ask him about this machine.",
						[4] = "Mezamir let you dive into the place he tried to discover years ago. Find a large staircase heading underwater on Pirate Island and find out what's below.",
						[5] = "You have found a shortcut to the deeplings' underwater base.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "IKEA for the BOLD",
			startStorageId = 11077,
			startStorageValue = 0,
			missions = {
				[1] = {
					name = "The Stocktaking",
					storageId = 11077,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 6,
					states = {
						[0] = "Commissioner Fisher has mentioned that Komor needs help.",
						[1] = "Komor needs help dealing with the disappearing furniture from his warehouse.",
						[2] = "Komor let you ask Gypsy if he knows anything about the theft of the furniture.",
						[3] = "Try to find the thief; he's possibly hiding in the sewers.",
						[4] = "You found the thief, but he managed to get away. Try to look around his hideout.",
						[5] = "You found a list of stolen items; the thief has apparently stolen more than just furniture. Go to Komor and give him the list.",
						[6] = "You helped Komor and got rewarded for that. You have started the new mission 'Needle in a Haystack'.",
					},
				},
				[2] = {
					name = "Needle in a Haystack",
					storageId = 11077,
					missionId = NextMissionId(),
					startValue = 6,
					endValue = 14,
					states = {
						[6] = "You helped Komor find his stolen furniture. Get your reward from the floor above if you haven't already. Visit Komor again to find out what he found on the list.",
						[7] = "Komor asked you to consult Commissioner Fisher about the thief.",
						[8] = "Fish asked you to track down the thief. Perhaps someone from nearby saw where he ran away?",
						[9] = "Find the bandit camp and see if they have anything to do with it.",
						[10] = "Ask the bandit leader about the furniture thief.",
						[11] = "Everything indicates that the thief is trying to smuggle items and hide in the steppes. The bandit leader suggested where you should go now.",
						[12] = "You have defeated the Lumberjack Domino, look around his hiding place.",
						[13] = "From now on, you can use his boat. Report to Commissioner Fisher.",
						[14] = "You finished the plot of Lumberjack Domino, from now on you can sail his boat from the bandit camp to the south of the steppes.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Settled down Fishmonger",
			startStorageId = Storage.UstatkowanyFanatyk.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Stagnation",
					storageId = Storage.UstatkowanyFanatyk.Mission01,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Anon's father is waiting for his order.",
						[2] = "You helped Anon's father recover his long-awaited package. Ask him for new mission now.",
					},
				},
				[2] = {
					name = "Milksop",
					storageId = Storage.UstatkowanyFanatyk.Mission02,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Anon's father needs help finding some old junk he carried with him for fishing. Search all boats, piers, and swamps around Mirko Town for any found items.",
						[2] = "You helped Anon's father collect his lost tools.",
					},
				},
				[3] = {
					name = "Stew for Trouble",
					storageId = Storage.UstatkowanyFanatyk.Mission03,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Anon's father received his table in a deplorable state, ask how you can improve his mood.",
						[2] = "Anon's father reacted strongly to the fact that someone destroyed his little table. Bring some of his favorite dishes, and he might calm down. Anon's father mentioned that he loves Rotworm Stew.",
						[3] = "You helped Anon's father with all the troubles. Now, go to his son for your reward.",
						[4] = "You have received a reward from the Fisherman Son. You gained the ability to purchase Shimmer Swimmer.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Cave Explorer on Shield",
			startStorageId = 8157,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "First Mission",
					storageId = 8158,
					missionId = NextMissionId(),
					startValue = -1,
					endValue = 7,
					states = {
						[-1] = "",
						[1] = "Find the page.",
						[2] = "You found the page, show it to Germi.",
						[3] = "Talk to Germi to get him to open the door for you.",
						[4] = "Find the Engineer's Ghost and help him.",
						[5] = "You've opened the gate, return to the Engineer.",
						[6] = "You greeted the Engineer, return to Germy.",
						[7] = "Mission completed.",
					},
				},
				[2] = {
					name = "Notes from the Conversation",
					storageId = 8159,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = { [1] = "", [2] = "cyk dwojeczka" },
				},
			},
		},
		[NextQuestId()] = {
			name = "Sultan Prime",
			startStorageId = Storage.SultanPrime.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "What Is Mafia? Is It Good?",
					storageId = Storage.SultanPrime.Mission01,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[2] = "You found the cursed amulet of power. Return it to the King of Phantasms so he can begin his world destruction plan.",
						[3] = "You returned the amulet to the Sultan and agreed to help him.",
					},
				},
				[2] = {
					name = "Unlucky Surveyors",
					storageId = Storage.SultanPrime.Mission02,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 7,
					states = {
						[1] = "Go to Sultan of Phantasms for another task.",
						[2] = "Sultan of Phantasms assigned you a task worthy of a novice villain. Poison the fountain in the town of Magicians using the poisoned flask.",
						[3] = "You've successfully completed the first task for Sultan of Phantasms. Return to him now.",
						[4] = "CAMELS_KILLED_STATUS",
						[5] = "You wiped out the camel farm. Leave the rope on the table - he'll know what to do with it.",
						[6] = "Sultan will be pleased with your actions. Return to him for your reward.",
						[7] = "Sultan rewarded you for your cooperation.",
					},
				},
				[3] = {
					name = "Sultan's Last Plague",
					storageId = Storage.SultanPrime.Mission03,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 6,
					states = {
						[1] = "OPENED_COFFINS_STATUS",
						[2] = "BODIES_THROWN_STATUS",
						[3] = "Hello, recipient. This is Sultan. It's time to get rid of Aspirant Ryba. After work, you can leave the barracks through the northern doors and use the shortcut.",
						[4] = "~Sultan. How did Ryba escape? The Crypt King also fell in battle. Come back immediately so I can chew you out!",
						[5] = "Sultan ordered you to.. You can go to Father Natanek and ask him for redemption.",
						[6] = "Father Natank gave you today's offering from today's Mass in exchange for your silence.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Assassins's Creed: Squurva'ali",
			startStorageId = Storage.AssassinsCreedSkurwoala.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "The First Step to Heaven",
					storageId = Storage.AssassinsCreedSkurwoala.Mission01,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "You agreed to help the ghost of the princess. Maybe some clergyman in town can help you.",
						[2] = "Father Natanek told you where to find Oldrak. Maybe he can help you.",
						[3] = "Oldrak didn't provide you with a solution, but he mentioned a magical carpet. Return to the princess now.",
						[4] = "You consulted with the ghost of the princess, who suggested you find the nomads' camp.",
					},
				},
				[2] = {
					name = "The Tailor's Touch",
					storageId = Storage.AssassinsCreedSkurwoala.Mission02,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					states = {
						[1] = "The ghost of the princess suggested asking the nomads for help - after all, the Aladdin stereotype didn't come out of nowhere.",
						[2] = "The nomad craftsman agreed to make a carpet for you. You will need 5 spider silk, a red pillow, and the artist palette that GM Tomek stole.",
						[3] = "Complete the exorcism ritual with Ryan - blame it on Tomek.",
						[4] = "Ryan gave you the palette stolen by Tomek. Now take it to Mareesha and create the carpet. You will need 5 spider silk, a red pillow, and the artist palette that GM Tomek stole.",
						[5] = "You've crafted the carpet with Mareesha. Now return to the ghost and make further plans.",
					},
				},
				[3] = {
					name = "Distant Calling",
					storageId = Storage.AssassinsCreedSkurwoala.Mission03,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "You acquired a carpet that doesn't have any special abilities. You can return to the Ghasstly Princess.",
						[2] = "Ghasstly Princess insisted that you go to Wilson Tag for help.",
						[3] = "Wilson Tag said that Djinn can definitely perform miracles like enchanting a carpet.",
					},
				},
				[4] = {
					name = "Djinn's Ordeal",
					storageId = Storage.AssassinsCreedSkurwoala.Mission04,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					states = {
						[1] = "Wilson Tag directed you to the Djinn, who is located somewhere at the desert.",
						[2] = "The Djinn instructed you on where to find the smugglers' base. Try to find something there that might interest him.",
						[3] = "You found a box of wafers that Djinn mentioned. Return to him and ask for his help with your task.",
						[4] = "Djinn agreed to help with 'enchanting' the carpet. Now find the missing dead weight, and Djinn will do his job.",
						[5] = "You delivered the materials needed for 'enchanting' the carpet to Djinn. From now on, you will be able to fly from the highest mountain in the Caribbean.",
					},
				},
				[5] = {
					name = "The Final Stretch",
					storageId = Storage.AssassinsCreedSkurwoala.Mission05,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					states = {
						[1] = "Go to the top of the highest mountain in the Caribbean, get on the enchanted carpet, and...",
						[2] = "Standing in front of the cave, ignite the flare given to you by the guardian to help the ghost.",
						[3] = "You ignited the flare in front of the ghost's cave. In the meantime, have a conversation with the ghost.",
						[4] = "At the moment when the undead king of the crypt was about to finish you, an angel arrived who managed to avoid the traps and teleport you to safety. You don't know his or the king of the crypt's fate. Seek advice from Father Natanek.",
						[5] = "Father Natanek informed you about the adverse consequences of the victory of the king of the crypt.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Resting Here",
			startStorageId = Storage.SpoczywajacyTutaj.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "A Work to Screw up",
					storageId = Storage.SpoczywajacyTutaj.Mission01,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Grave digger gave you a special crowbar. Try to find a use for it.",
						[2] = "You found some kind of last will. Try to find the item mentioned in it.",
						[3] = "You found a document that indicates that four people broke into the labyrinth. At least two of them are no longer alive. Try to find one of the survivors.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Chester the Dwarf",
			startStorageId = Storage.CzeslawKrasnolud.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Fortune Teller 3000",
					storageId = Storage.CzeslawKrasnolud.Mission01,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 2,
					states = {
						[1] = "You agreed to help Chester become a TV fortune teller. He will need the following items for his profession: Magic Light Wand, Empty Goldfish Bowl, Magician's Robe, Life Crystal.",
						[2] = "Chester the Dwarf has become a fortune teller, and you received his pickaxe as a reward.",
					},
				},
				[2] = {
					name = "Chester the Turf Accountant",
					storageId = Storage.CzeslawKrasnolud.Mission02,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "You helped Chester the Dwarf with his TV fortune teller career. Ask him later if he needs help in another field.",
						[2] = "Chester the Dwarf entrusted you with a very discreet task. Obtain a new set of documents for him. He directed you to Andrew The Moustachizzle, the leader of the bandits at the camp near Mirkotown.",
						[3] = "You obtained the documents from Ornuld. Now, deliver them to Chester the Dwarf.",
						[4] = "You acquired new documents for Chester the Dwarf, and he rewarded you for it.",
					},
				},
				[3] = {
					name = "Mirko Train Simulator",
					storageId = Storage.CzeslawKrasnolud.Mission03,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "You helped Chester the Dwarf change his identity. Ask him later if he needs help in another field.",
						[2] = "Chester the Dwarf wants to sail away from the continent on his steamship. Find the entrance to the shaft leading to his ship.",
						[3] = "You found the cave that Chester the Dwarf was looking for. Now, return to him with the good news.",
						[4] = "You helped Chester the Dwarf with his life problems. He has started packing to begin anew far, far away from here.",
					},
				},
				[4] = {
					name = "Business Class to the Labour Exchange",
					storageId = Storage.CzeslawKrasnolud.Mission04,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Chester the Dwarf has disappeared from the continent. Or has he? Maybe he hasn't managed to start the steamship underground yet. If possible, catch up to him and stop him.",
						[2] = "Chester gave you Gandalf's lost item. Now, return to the mighty wizard and return his property.",
						[3] = "Gandalf rewarded you for recovering his bag.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Path of the Undead",
			startStorageId = Storage.SciezkaNieumarlych.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Test of Strength",
					storageId = Storage.SciezkaNieumarlych.Mission01,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 2,
					states = {
						[1] = "Gandalf told you about the history of Mirkotown. Now, ask him what conditions you need to fulfill to get his help.",
						[2] = "Gandalf promised to bless your cause, but first, you must visit special magical circles.",
					},
				},
				[2] = {
					name = "Endurance Test",
					storageId = Storage.SciezkaNieumarlych.Mission02,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 2,
					states = {
						[1] = "Gandalf promised to bless your cause, but first, you must visit special magical circles.",
						[2] = "Gandalf has blessed you and advised you to go to Konmuld for further instructions.",
					},
				},
				[3] = {
					name = "The Final Battle",
					storageId = Storage.SciezkaNieumarlych.Mission03,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Gather the necessary items, summon, and ultimately defeat the Undead Crypt King.",
						[2] = "You have defeated the Undead Crypt King. Return to Gandalf for your reward.",
						[3] = "Gandalf misplaced a certain item intended as a reward, but you have received his other gifts.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "King of Rats Headquarters",
			startStorageId = Storage.KrolSzczurowHub.Questline,
			startStorageValue = 0,
			missions = {
				[1] = {
					name = "CurentStatus",
					storageId = Storage.KrolSzczurowHub.Questline,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = TableSize(Storage.KrolSzczurowHub.Items),
					description = "King of Rats Headquarters Status",
				},
				[2] = {
					name = "01. to Ryan",
					storageId = Storage.KrolSzczurowHub.Portals.Ryan,
					missionId = NextMissionId(),
					startValue = -1,
					endValue = 1,
					description = "You unlocked this teleport",
				},
				[3] = {
					name = "02. to Sweaty Cyclops",
					storageId = Storage.KrolSzczurowHub.Portals.SweatyCyclops,
					missionId = NextMissionId(),
					startValue = -1,
					endValue = 1,
					description = "You unlocked this teleport",
				},
				[4] = {
					name = "03. to Djinns",
					storageId = Storage.KrolSzczurowHub.Portals.Djinns,
					missionId = NextMissionId(),
					startValue = -1,
					endValue = 1,
					description = "You unlocked this teleport",
				},
				[5] = {
					name = "04. to North Kongo",
					storageId = Storage.KrolSzczurowHub.Portals.NorthKongo,
					missionId = NextMissionId(),
					startValue = -1,
					endValue = 1,
					description = "You unlocked this teleport",
				},
				[6] = {
					name = "05. to Werebadgers",
					storageId = Storage.KrolSzczurowHub.Portals.Werebadgers,
					missionId = NextMissionId(),
					startValue = -1,
					endValue = 1,
					description = "You unlocked this teleport",
				},
				[7] = {
					name = "06. to Vampire city",
					storageId = Storage.KrolSzczurowHub.Portals.VampireCity,
					missionId = NextMissionId(),
					startValue = -1,
					endValue = 1,
					description = "You unlocked this teleport",
				},
				[8] = {
					name = "07. to Asuras",
					storageId = Storage.KrolSzczurowHub.Portals.Asuras,
					missionId = NextMissionId(),
					startValue = -1,
					endValue = 1,
					description = "You unlocked this teleport",
				},
				[9] = {
					name = "08. to East Hurgahada",
					storageId = Storage.KrolSzczurowHub.Portals.HurghadaEast,
					missionId = NextMissionId(),
					startValue = -1,
					endValue = 1,
					description = "You unlocked this teleport",
				},
			},
		},
		[NextQuestId()] = {
			name = "Theater of Cheap Thrills",
			startStorageId = Storage.TeatrTaniejSensacji.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "01. Vitat Iustitia",
					storageId = Storage.TeatrTaniejSensacji.Mission01,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[0] = "State 0",
						[1] = "Many people ask: Who is this King of Rats and what's the deal? That's when I tell them, 'You stinker, go to Ratland and see for yourself. The King of Rats! Lets go! Yeehaw!",
						[2] = "Romek assigned you the task of finding mature cheese in the pirates' hideout.",
						[3] = "Chorus of Januses: A strange trumpet will spread a sound, fire will coagulate, the light will dim, and the world's history will turn to dust. From the trees of eternity, leaves will fall on the Judge's dreadful coming to bear witness to the Psalmist.",
					},
				},
				[2] = {
					name = "02. I'm Not a Rat's Fugue",
					storageId = Storage.TeatrTaniejSensacji.Mission02,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[0] = "State 0",
						[1] = "Romek has offered you a position as his assistant. However, you must first pass a fair test.",
						[2] = "Pass the fair test to become the King of Rats assistant.",
						[3] = "Chorus of Januses: My radiance will pierce the Darkness, My brilliance will scatter the Shadows, ~Your father drunkard after a case of beers.",
					},
				},
				[3] = {
					name = "03. Good Day, Mrs. Pitca",
					storageId = Storage.TeatrTaniejSensacji.Mission03,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[0] = "State 0",
						[1] = "Romek needs help with a new task. Go to him.",
						[2] = "Defeat Romek's supposed enemy, Mrs. Pitca.",
						[3] = "You defeated Mrs. Pitca, now return to Romek.",
						[4] = "Chorus of Januses: MU-MU-MURDERER! MU-MU-UUUU-MURDERER! MU-murderer! MUU-MURDERER!",
					},
				},
				[4] = {
					name = "04. Vanitas vanitatum et omnia vanitas",
					storageId = Storage.TeatrTaniejSensacji.Mission04,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[0] = "State 0",
						[1] = "Romek needs help with a new task. Go to him.",
						[2] = "Romek mentioned that Grave Digger might know how to remove curses. Try to get the necessary information from him.",
						[3] = "You found a book that can help Romek. Return to him and give it to him.",
						[4] = "Chorus of Januses: Let us rejoice, brothers! Enough of tears! Our victory is complete! To the fighters, honor, to the fallen, respect! Let the earth carry a laudatory song! We poured sweat and blood But our glory is against the enemy! Although each of us has lost much, Let us rejoice, brothers! It's time for victory!",
					},
				},
				[5] = {
					name = "05. Ham from under the Rug",
					storageId = Storage.TeatrTaniejSensacji.Mission05,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					states = {
						[1] = "Romek needs help with a new task. Go to him.",
						[2] = "Romek has assigned you the task of catering his kebab party.",
						[3] = "Shivganesh needs three garlic heads and payment for making the kebabs.",
						[4] = "Shivganesh has promised to deliver the kebabs on time. Deliver the good news to Romek.",
						[5] = "Chorus of Januses: How great is the peace gained by one who does not heed what a neighbor says, does, or thinks, but only what they themselves do, to be just and godly.",
					},
				},
				[6] = {
					name = "06. Holiday Camp, you know where",
					storageId = Storage.TeatrTaniejSensacji.Mission06,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					states = {
						[0] = "State 0",
						[1] = "GM Romek needs help with a new problem, go to him.",
						[2] = "Organize a camp for Romek's son, Kitz. Arni will assist you with this task.",
						[3] = "Inform Kitz that his trip is ready.",
						[4] = "You have completed the task for Romek. Return to him now for your reward.",
						[5] = "Chorus of Januses: Peace on all peaks. In leaves, in valleys Nothing.",
					},
				},
				[7] = {
					name = "07. King of Rats' Gambit",
					storageId = Storage.TeatrTaniejSensacji.Mission07,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[0] = "State 0",
						[1] = "GM Romek needs help with a new problem, go to him.",
						[2] = "GM Romek is afraid for his life. Try to find Robercik before he finds Romek.",
						[3] = "You defeated the cunning Robercik. Return to Romk for your reward.",
						[4] = "Chorus of Januses: I was sent to break the chains of justice. This time, he will perish along with his soul.",
					},
				},
				[8] = {
					name = "08. The Art That of Just",
					storageId = Storage.TeatrTaniejSensacji.Mission08,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "GM Romek needs help with a new problem, go to him.",
						[2] = "GM Romek will be waiting for donations until his death. It's better to support him.",
						[3] = "GM Romek has accepted your donation. Return to him when the festival is over.",
						[4] = "Chorus of Januses: Iuvenes inconsiderate patrum suorum errata repetunt. Canem me rape cum cacat.",
					},
				},
				[9] = {
					name = "09. Abyssal Chasms of Decadence",
					storageId = Storage.TeatrTaniejSensacji.Mission09,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "GM Romek needs help with a new problem, go to him.",
						[2] = "GM Romek is starting a new minecraft server. Tell Wilson, a frequent visitor to old school servers, about Romek's known scams and acts of corruption.",
						[3] = "You tipped off Wilson. Now return to Romek and observe his reaction.",
						[4] = "Chorus of Januses: The human form is above spider filth. Cunning is a virtue; the king of rats is a coward.",
					},
				},
				[10] = {
					name = "10. Cocoa Intruder",
					storageId = Storage.TeatrTaniejSensacji.Mission10,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "GM Romek needs help with a new problem, go to him.",
						[2] = "GM Romek instructed you to find the map of the leader of the southern Orcs.",
						[3] = "You obtained information about the location of Brazil. Pass the gathered information to Romek.",
						[4] = "Chorus of Januses: Honor the deceased - a worthy act. But breaking the law, striking down the government, you drunk on your own sins!",
					},
				},
				[11] = {
					name = "11. The Work of Destruction",
					storageId = Storage.TeatrTaniejSensacji.Mission11,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[0] = "State 0",
						[1] = "GM Romek needs help with a new problem, go to him.",
						[2] = "You learned that King Juerdo Titsgo is ddosing Romek's server. He should be hiding in the vicinity of Brazilian Rats' Land. Knock him out so that Romek can run the server peacefully.",
						[3] = "You gave Juerdo a beating. Return to Romek for your reward.",
						[4] = "Chorus of Januses: He will be the patron of chances! For the work of destruction in a good cause is holy, like the work of creation. The king renounced his word - become a king and perish. When faith and freedom escape from people.",
					},
				},
				[12] = {
					name = "12. Forever and Ever Ytong",
					storageId = Storage.TeatrTaniejSensacji.Mission12,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[0] = "State 0",
						[1] = "The lives of the rats are in danger! Hurry to Romek.",
						[2] = "Romek has ordered you to commit ratocide. Carry out his will and don't ask questions.",
						[3] = "Chorus of Januses: We won't leave the land where we were born! It's written in our atlases! Justice will come in a stench! Do you know who ran over whom on the zebra crossing? Three Januses sing soprano: The time for trials has come! Give us a knife! Give us a knife! Our rich neighbor won't be! Go on, cut! Go on, cut! fat Janus the baritone: LET'S KILL THEM!",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Safety and Occupational Hygiene",
			startStorageId = Storage.BezpieczenstwoIHigienaPracy.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "01. Avast ye, scallywag!",
					storageId = Storage.BezpieczenstwoIHigienaPracy.Mission01,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[0] = "GM Romek needs help with a new problem, go to him.",
						[1] = "Find Turdstin - he might know where the Rat of Kings is.",
						[2] = "Try to convince Xe'na to remove the cuckcurse from Turdstin.",
						[3] = "Xe'na refused to help Turdstin. Go back to him and deliver the news.",
						[4] = "Chorus of Januses:\nIn our homeland, injustices abound,\nNo one will erase them with a hand,\nBut no one is a blood relative here:\nWe'll drain it from our chests and mold it.",
					},
				},
				[2] = {
					name = "02. Eww. Am I the only one there to hate the womyn?",
					storageId = Storage.BezpieczenstwoIHigienaPracy.Mission02,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Turdstin thanked you for the information that the only way to find the Rat of Kings is by listening to the Januses' choir. Talk to him again for a new mission.",
						[2] = "Turdstin asked for your help in collecting cans.",
						[3] = "Chorus of Januses:\nWhen the evening stars extinguish,\nBefore I put the metal detector in the box,\nI offer my prayers,\nTo God the Father and the Son.\nLet's screw over the neighbor!",
					},
				},
				[3] = {
					name = "03. Vicinities Lost",
					storageId = Storage.BezpieczenstwoIHigienaPracy.Mission03,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Turdstin mentioned that he will need assistance.",
						[2] = "Turdstin needs help with the Emperor's workers and hooligans.",
						[3] = "Chorus of Januses:\nUnclean forces threaten you,\nLet us gain fame, oh Christ!\nMatthew, Brian insulted us!\nWe'll lift the burden of the cross!",
					},
				},
				[4] = {
					name = "04. Very Important Posts",
					storageId = Storage.BezpieczenstwoIHigienaPracy.Mission04,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Turdstin mentioned that he might have a new task for you.",
						[2] = "Turdstin found a fake premium account on 4chan. Try to bribe Xe'na.",
						[3] = "Your mother, grandmother, and sister are insane\nOn the eastern borders, there's a path that's not cursed upon any name\nDragons and others were brought there by a rocket\nTo avoid looking like a fool, keep a salmon in your pocket.",
					},
				},
				[5] = {
					name = "05. Hydrofoils with Seasoning",
					storageId = Storage.BezpieczenstwoIHigienaPracy.Mission05,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "You handed over the premium account to Xe'na. And now...",
						[2] = "You fed the exhausted Rat of Kings. Now ask him about the mission.",
						[3] = "Chorus of Januses:\nGrant us some heavenly grace!\nLet us kill Peter in return!\nShow your love to others\nTo us - JUSTICE!",
					},
				},
				[6] = {
					name = "06. Crinjeux",
					storageId = Storage.BezpieczenstwoIHigienaPracy.Mission06,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					states = {
						[1] = "The Rat of Kings told you that Petrus Ciemiezca is on the peak of the magician's rocks to the northeast of Mirkotown.",
						[2] = "You defeated Petrus Ciemiezca. Find the Ytong of Power. It must be hidden somewhere in the tower.",
						[3] = "You found the Ytong of Power. Now, return to the Rat of Kings.",
						[4] = "The Rat of Kings revealed information to you about the looming threat- HF-P/X. Go back to Romek and hear his opinion on the matter.",
						[5] = "Chorus of Januses:\nI want to go to the only place on Earth,\nWhere the darkness no longer matters,\nTo the beings who accept my abilities as divinely,\nTo them I aspire, only to my justice.\nThere is one small place on Earth for me,\nWhere nothing else matters beyond the mushroom from the grout,\nI escape there with all my justice,\nI believe in you, I believe in my Brother-in-law.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "The Three Sramatians and the Dragon",
			startStorageId = Storage.TrzejSramaciISmok.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "01. Hither and Thither",
					storageId = Storage.TrzejSramaciISmok.Mission01,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 1,
					states = {
						[1] = "And the men went along the road into the woods,\nWith an average pace,\nHumility will come for them in due time,\nEnter the lower text here.",
					},
				},
				[2] = {
					name = "02. Fungus Magnum",
					storageId = Storage.TrzejSramaciISmok.Mission02,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "I think the company went east of the northern gate of Mirkotown. From there, they went into the forest of idiots. In the forest, there's a secret passage through the caves of disgusting trolls. They might have used it. ~GM Romek",
						[2] = "You correctly answered Goldblum's riddle. Now give him your best puzzle.",
						[3] = "Respiciens post te, hominem\nmemento te; cave, ne cadas",
					},
				},
				[3] = {
					name = "03. Follow OSHA Standards",
					storageId = Storage.TrzejSramaciISmok.Mission03,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					states = {
						[1] = "Goldblum said that Bilbeus's company might be around the hive.",
						[2] = "Ask Bilbeus how you can join their company.",
						[3] = "Find a box of rum in the pirate village nearby.",
						[4] = "You found rum for Bilbeus. Return to him and suggest that he indulge himself.",
						[5] = "An unworthy act for a Builder\nThe King will probably put his balls in blender",
					},
				},
				[4] = {
					name = "04. Delirium Tremens",
					storageId = Storage.TrzejSramaciISmok.Mission04,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Find the company's camp in the western steppes.",
						[2] = "You found the camp, but the company has already moved on. They might have settled in the nearest human town.",
						[3] = "Now it's time to search for valuable renewable resources for the Recycling Father.",
					},
				},
				[5] = {
					name = "05. Aqua Inaestimabilis",
					storageId = Storage.TrzejSramaciISmok.Mission05,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 6,
					states = {
						[1] = "Bilbeus came up with the idea to steal wine from the vampires. New wine deliveries appear at the docks not only on Sundays at noon.",
						[2] = "Find a way to escape the dungeons, then locate Gertrude.",
						[3] = "Gertrude told you that the company went to the desert. The Djinn Lord - Jannah'ma might help you find them.",
						[4] = "Jannah'ma demanded dragon meat in exchange for information about your companions.",
						[5] = "Jannah'ma indicated that the company is by the old mine, where wyverns nest.",
						[6] = "An old unjust man again dragged me into trouble.",
					},
				},
				[6] = {
					name = "06. Shepherd of Rats",
					storageId = Storage.TrzejSramaciISmok.Mission06,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "Bilbeus mentioned that you should head to the nomad's rock.",
						[2] = "The Nomad asked for a favor - he wants a crystal from the depths.",
						[3] = "Return to Bilbo and tell him what you learned from the nomad.",
						[4] = "Fing\nfurious\nup to the sky, the SKY\nTO HELL,\nUUU",
					},
				},
				[7] = {
					name = "07. Nasty Neighbor Abominable Cravings",
					storageId = Storage.TrzejSramaciISmok.Mission07,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "Go to the lizard people's village and find the ancient artifact.",
						[2] = "Bilbeus mentioned earlier that they will stop at Hairycles's place.",
						[3] = "Bilbeus wants to repay Hairycles for the information he provided. Bring some bananas to Bilbeus.",
						[4] = "Sheeit, it's awesome.",
					},
				},
				[8] = {
					name = "08. Follow the Odor of Opulence",
					storageId = Storage.TrzejSramaciISmok.Mission08,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Bilbeus indicated that they are heading to the Temple of Hellspawn.",
						[2] = "Find three magic runes to unlock the doors deep inside the temple.",
						[3] = "I saw a snail crawling along the edge of a razor. It's my dream. My nightmare born from hell. It plods, crawls along the devilishly sharp razor edge. And it doesn't die.",
					},
				},
				[9] = {
					name = "09. Artificial Intelligence and Euthanasia",
					storageId = Storage.TrzejSramaciISmok.Mission09,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "The Rat of Kings took the runes from you and unsealed the door. Now find HF-P/X.",
						[2] = "Return to the Rat of Kings and tell him about the battle.",
						[3] = "The Rat of Kings had a heart attack upon hearing about so many wrecked Passats. Now, go back to Romek.",
						[4] = "Greed consumed you\nAbove creativity, attention-seeking\nAbove reason, fame\nProfit to the bottom, the worthy are hunted\nLack of a healthy foundation.\nYou killed my child in horror\nThe end of the world is coming.\nCanary, Russia, Bitcoins, Ameno.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Four Act Tragedy",
			startStorageId = Storage.TragedyaWCzterechAktach.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "01. Dodge those compensation claims",
					storageId = Storage.TragedyaWCzterechAktach.Mission01,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "Romek mentioned you should as him for mission.",
						[2] = "Go to HF-P/X agent - turdstin.",
						[3] = "Return to romek and talk to him about HF-P/X case.",
						[4] = "Romek sent you to Knurow. Try to find a way to go back in time there.",
					},
				},
				[2] = {
					name = "02. Bottom tex_L",
					storageId = Storage.TragedyaWCzterechAktach.Mission02,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 6,
					states = {
						[1] = "Find someone who can show you around.",
						[2] = "Timmy asked you to find his equipment that was stolen by bandits.",
						[3] = "You found timmy belongings. Return to him and give them back.",
						[4] = "Timmy needs elvish dust to perform his magic. Try finding it on nearby mountain.",
						[5] = "Timmy told you that he will already have helped you in the future. Go back to Romek.",
						[6] = "You told romek about Timmy work.",
					},
				},
				[3] = {
					name = "03. Master Baitor",
					storageId = Storage.TragedyaWCzterechAktach.Mission03,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Romek asked you to buy him a beer at nearby Lewiatan.",
						[2] = "You defeated the kraken. Go back to Romek.",
						[3] = "Find slippers bitten by the Rat Bum. Romek mentioned northern rat collaborators as his allies.",
					},
				},
				[4] = {
					name = "04. Non omnis moriar",
					storageId = Storage.TragedyaWCzterechAktach.Mission04,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Find slippers bitten by the Rat Bum. Romek mentioned northern rat collaborators as his allies.",
						[2] = "You found the Bribeslippers. Report back to Romek.",
						[3] = "Romek told you to follow the trail leading to the frog cult altar. Search the northern kongo.",
					},
				},
				[5] = {
					name = "05. Enqueued for a Genocide",
					storageId = Storage.TragedyaWCzterechAktach.Mission05,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Romek told you where to start looking for frog cult altar.",
						[2] = "You defeated the Skurwiwij. Report back to Romek.",
						[3] = "Ask Xena for possible usage for Grazhenacore.",
					},
				},
				[6] = {
					name = "06. Sic transit gloria mundi",
					storageId = Storage.TragedyaWCzterechAktach.Mission06,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					states = {
						[1] = "Ask Xena for possible usage for Grazhenacore.",
						[2] = "Try to find Grazhena deep under Hero caves.",
						[3] = "Rat Bum ran away to his cave. Chase him!",
						[4] = "You defeated the Rat Bum. Go back to Romek.",
						[5] = "You helped Romek in dealing with Rat Bum. He rewarded you for your effort.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Per Iustitia Ad Astra",
			startStorageId = Storage.PerIustitiaAdAstra.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "01. Beyond the Justice",
					storageId = Storage.PerIustitiaAdAstra.Mission01,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Go to the highest mountain in the Kraiby and look for someone Romek mentioned.",
						[2] = "Astral Janus told you about a new threat. Proceed talking to gain more information.",
						[3] = "Astral Janus mentioned that you should start by fiding Yaan'Usha forge.",
					},
				},
				[2] = {
					name = "02. So-called Life",
					storageId = Storage.PerIustitiaAdAstra.Mission02,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "Head to the Yaan'Usha forge and find Qasim.",
						[2] = "Collect all the starship parts mentioned by Qasim.",
						[3] = "You collected ship parts requested by Qasim. Now try finding jet engine plans and three star maps.",
						[4] = "Qasim catapulted your ship to the orbit. Try to board it through teleporting device.",
					},
				},
				[3] = {
					name = "03. Cosmo Petrol Natural",
					storageId = Storage.PerIustitiaAdAstra.Mission03,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					states = {
						[1] = "Board your ship through unlicensed teleporting device in deepling temple.",
						[2] = "You found a place where you can board your ship. Try too look around.",
						[3] = "Help Swagger find his lost crate. He sent information about ganymede to your ship.",
						[4] = "Your found Swagger crate. Return to him now.",
						[5] = "You returned crate to Swagger.",
					},
				},
				[4] = {
					name = "04. Bobsleigh to Oven",
					storageId = Storage.PerIustitiaAdAstra.Mission04,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 7,
					states = {
						[1] = "Swagger told you about some men transporting *REDACTED* to hugo cottage house. Investgiate that.",
						[2] = "You found Rubelstein in prison cell. He asked you to grab keys from locker on upper floor.",
						[3] = "You found identity document in wardrobe. Report back to rubelstein.",
						[4] = "Try to talk to officer on top of the tower.",
						[5] = "You talked to the officer and saved Rubelstein. Now ask Klaus about the mission.",
						[6] = "You talked to the officer and betrayed Rubelstein. Now ask Klaus about the mission.",
						[7] = "Head to Hugo planet and tell him about the mission you have been assigned.",
					},
				},
				[5] = {
					name = "05. Put on the 3D glasses",
					storageId = Storage.PerIustitiaAdAstra.Mission05,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 10,
					states = {
						[1] = "Find hugo on his planet and tell him about Ubefabrik plans.",
						[2] = "Hugo noticed that your accent is off, also he knew the person you are impersonating. Improvise.",
						[3] = "Find Hugo recipe for his favourite drink.",
						[4] = "You found Hugo's recipe. Report back to him.",
						[5] = "Find hammer in Lecima shithole and repair pipe is castle sewers.",
						[6] = "You repaired the faulty sewer pipe. Report back to hugo",
						[7] = "Hugo told you to search the basement of his castle and find and open special chest.",
						[8] = "You opened the magic chest. Report back to Hugo.",
						[9] = "Hugo told you that you can keep the experience you got from chest. Ask him for new mission.",
						[10] = "Hugo asked you to deal with something lurking in southern beach.",
					},
				},
				[6] = {
					name = "06. I Don't Brush My Teeth. How Did You Know?",
					storageId = Storage.PerIustitiaAdAstra.Mission06,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "Hugo asked you to deal with something lurking in southern beach.",
						[2] = "You killed the monster menacing the beach. Report to Hugo.",
						[3] = "Hugo told you about ancient artifact buried somewhere in the northern dump.",
						[4] = "You found an ancient artifact. Report to Astral Janus.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Prodigal Son",
			startStorageId = Storage.SynMarnotrawny.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "01. Work is da poop!",
					storageId = Storage.SynMarnotrawny.Mission01,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					states = {
						[1] = "Ask Chester for a new mission.",
						[2] = "Find the metro leading to workplace designated by Chester.",
						[3] = "You found the metro Chester was talknig about. Try to find the work supervisor when you arrive at the next station.",
					},
				},
				[2] = {
					name = "02. Artisan Baker",
					storageId = Storage.SynMarnotrawny.Mission02,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					states = {
						[1] = "Find the work supervisor.",
						[2] = "Henry commanded you to start your new job: painting wooden hammers. He asked for 5 pieces.",
						[3] = "Henry gave you a new job: make 5 calculators.",
						[4] = "Henry ordered 5 new pliers.",
						[5] = "You completed all of Henry's orders.",
					},
				},
				[3] = {
					name = "03. Cheetos Prank Acedemy",
					storageId = Storage.SynMarnotrawny.Mission03,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 6,
					states = {
						[1] = "Henry promoted you to an assistant position. Ask for your new duties.",
						[2] = "Henry asked you to investigate the ever-shrinking number of towels and soaps in toilets.",
						[3] = "You handed the missing soaps to Henry. Ask him for a new mission.",
						[4] = "Areczeks are trying to unionize. Defeat their leader and the union may dissolve.",
						[5] = "Areczek union leader promised to dissolve their union. Report back to Henry.",
						[6] = "Henry is content that you busted the union.",
					},
				},
				[4] = {
					name = "04. Serious business",
					storageId = Storage.SynMarnotrawny.Mission04,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "Ask Henry for your next mission.",
						[2] = "Find the three books on eristics. Henry lost them allover the place.",
						[3] = "Henry granted you the mighty powers of eristics. Try to persuade the customers in conference hall to buy company products.",
						[4] = "Henry thanked you for doing your job.",
					},
				},
				[5] = {
					name = "05. SUPREME",
					storageId = Storage.SynMarnotrawny.Mission05,
					missionId = NextMissionId(),
					startValue = 0,
					states = {
						[1] = "Ask Henry for new mission.",
						[2] = "Henry asked you to find a gray-haired dwarf corpse.",
						[3] = "You gave Henry his lost necklace. Ask him for new mission.",
						[4] = "Check the silo state in the lava mines.",
						[5] = "You used special machine to check state of the silo content. Report back to Henry.",
						[6] = "Henry told you about a friend stuck on north-eastern mines. Escort him back to Henry.",
						[7] = "Henry asked you to give him a moment to discuss something with his friend Fredi.",
						[8] = "Henry thanked you for doing your job.",
					},
				},
				[6] = {
					name = "06. Coup d'Passat",
					storageId = Storage.SynMarnotrawny.Mission06,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					states = {
						[1] = "Henry told you to find the password to the royal room.",
						[2] = "You defeated Pol, the boss-imperator of Januszex. Report to Henry.",
						[3] = "Henry finally gave you the payslip you needed. Go back to Chester.",
						[4] = "Im a dog, and you are a flower.\nIf i lift my leg i might give you a shower.",
					},
				},
			},
		},
	}
end

local function normalizeQuestData()
	for questId, quest in pairs(Quests) do
		for missionNumber, mission in pairs(quest.missions) do
			mission.endValue = mission.endValue or #mission.states
		end
	end
end
normalizeQuestData()
