-- ToDo: github
-- https://vypas.com/d/rme_source.zip

NEXT_QUEST_ID = NEXT_QUEST_ID or 0
function NextQuestId()
	NEXT_QUEST_ID = NEXT_QUEST_ID + 1
	return NEXT_QUEST_ID
end

NEXT_MISSION_ID = NEXT_MISSION_ID or 0
function NextMissionId()
	NEXT_MISSION_ID = NEXT_MISSION_ID + 1
	return NEXT_MISSION_ID
end

TASKS_QUEST_STORAGE = NextQuestId()
DAILY_TASK_STORAGE = NextQuestId()

if not Quests then
	Quests = {
		[TASKS_QUEST_STORAGE] = {
			name = "Tasks",
			startStorageId = Storage.Tasks.TaskInfo,
			startStorageValue = 0,
			missions = {
				[1] = {
					name = "Task informations",
					storageId = Storage.Tasks.TaskInfo,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 1,
					description = "TASKS_HELP_WINDOW_INFO",
				},
			},
		},
		[DAILY_TASK_STORAGE] = {
			name = "Daily task",
			startStorageId = Storage.DailyTasks.DailyTaskInfo,
			startStorageValue = 0,
			missions = {
				[1] = {
					name = "Daily tasks information",
					storageId = Storage.DailyTasks.DailyTaskInfo,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 1,
					description = "DAILY_TASKS_HELP_WINDOW_INFO",
				},
			},
		},
		[NextQuestId()] = {
			name = "Arena",
			startStorageId = 300,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "First arena",
					storageId = 301,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "Kill:\nFrostfur\nBloodpaw\nBovinus\nAchad\nColerian the Barbarian\nThe Hairy One\nAxeitus Headbanger\nRocky\nCursed Gladiator\nOrcus the Cruel",
				},
				[2] = {
					name = "Second arena",
					storageId = 302,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "Kill:\nAvalanche\nKreebosh the Exile\nThe Dark Dancer\nThe Hag\nSlim\nGrimgor Guteater\nDrasilla\nSpirit of Earth\nSpirit of Water\nSpirit of Fire",
				},
				[3] = {
					name = "Third arena",
					storageId = 303,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "Kill:\nWebster\nDarakan the Executioner\nNorgle Glacierbeard\nThe Pit Lord\nSvoren the Mad\nThe Masked Marauder\nGnorre Chyllson\nFallen Mooh'Tah Master Ghar\nDeathbringer\nThe Obliverator",
				},
				[4] = {
					name = "Fourth arena",
					storageId = 304,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "Arena, extreme level.",
				},
			},
		},
		[NextQuestId()] = {
			name = "Firestarter",
			startStorageId = 11009,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Mission 1: Fiery Beginnings",
					storageId = 11009,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Hymel asked you to burn down the herbs he left on his house on north side of MikroTown.",
						[2] = "You burnt the herbs, now talk again with Hymel.",
						[3] = "Hymel gave you an incendiary firebug. From now on you can buy more firebugs from him.",
					},
				},
				[2] = {
					name = "Mission 2: Little Treat",
					storageId = 11010,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Hymel want to mischief the local guards, by setting an old tree on fire. You can find it near their resting camp.",
						[2] = "You did it, the guards didn't even notice, go back and see Hymel.",
						[3] = "In return for your help, Hymel gave you the staff of a real reefer.",
					},
				},
				[3] = {
					name = "Mission 3: How High",
					storageId = 11011,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Hymel told you about how he and his mates once sowed 5 mysterious herbs all around MirkoTown. Unfortunately he doesn't remember where exactly they did sow them. They look like usual red flowers. Find them and set them ablaze with firebug.",
						[2] = "The smell of weed is now around the whole city, you managed to burn all the flowers.",
						[3] = "Hymel made you a true pyromaniac and gave you his arsonist weapon.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "The Way of a Druid",
			startStorageId = 11007,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "The Council of Druids",
					storageId = 11007,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 7,
					states = {
						[1] = "You met one of the druids, if you helped him, he would tell you about the Council.",
						[2] = "You helped the first druid. This is the beginning of your journey to become one of them. Find the remaining druid, and provide them with your help.",
						[3] = "The Mother Nature is watching, and she is cherishing as you helped two of the druids.",
						[4] = "Your efforts induced The Mother Nature let you gather water from well at the great tree.",
						[5] = "You drew water from well at the sacred tree. Now try to find the next druid.",
						[6] = "Your kindness goes a long way, you helped four druids so far.",
						[7] = "You helped all the druids, and you have been introduced to their Council. Now you can harvest a blossom of the Griffinclaw plant, which grows inside a great tree.",
					},
				},
				[2] = {
					name = "Deer Season",
					storageId = 11008,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Radaghast asked you to burn down the hunters' stock of wood. This should prove to help a lot of animals to survive during the hunting season.",
						[2] = "You managed to burn down the stock of wood in the hunters' village. Make haste and tell about this to Radaghast.",
						[3] = "Radaghast handed you a slingshot for your help, also he erranded you to help other druids from the council he told you about.",
					},
				},
				[3] = {
					name = "Taken: Benek",
					storageId = 11017,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Estep is Wailing since orcs taken his Wolf companion.",
						[2] = "The wolf has been freed, deliver a good message to Estep.",
						[3] = "Estep handed over this knife in his gratitude.",
					},
				},
				[4] = {
					name = "Rude eviction",
					storageId = 11061,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "SandNigger asked you to help him reclaim his secret spell.",
						[2] = "You managed to find and combust the spell, come back to Sandnigger.",
						[3] = "For your kind deed, you have been granted The Lion Amulet.",
					},
				},
				[5] = {
					name = "The secret ingredient",
					storageId = 11067,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Mundral asked you to get the medicine for his sick pet. You can ask Ornuld for it.",
						[2] = "Turn out that Mundral belongs to the Druid Council. He put in a good word to his druid friends and he gifted you with bamboo leaves.",
					},
				},
				[6] = {
					name = "The Ornuld's medicine",
					storageId = 11068,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Ornuld wishes to have a one wyrm egg. If you manage to do this favor, he will reward you with the medicine.",
						[2] = "You found the wyrm's egg, hand it to Ornuld.",
						[3] = "Ornuld gave you the medicine in exchange for the wyrm's egg.",
					},
				},
				[7] = {
					name = "The Singing Crystal",
					storageId = 11069,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Malfurion is in need of an ice crystal fragment for his experiment.",
						[2] = "You managed to gather a bunch of crystal, go back to Malfurion.",
						[3] = "For your help, Malfurion gave you a gift.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Ariel's Friend",
			startStorageId = 11000,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Helping the Ariel",
					storageId = 11000,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Ariel asked you to bring him his friend's favorite flower. Namely it is the Heaven Blossom. Some elves keep it in their pouch.",
						[2] = "Ariel asked you to pay respect to his friend by laying these flowers on his grave. It is located on a nearby hill. If you do that, he will tell you his story.",
						[3] = "You put the flowers on Ariel's friend's grave, now come back to Ariel.",
						[4] = "Ariel endowed you with a bow and a few minor gifts. He is now ready to tell you his story, whenever you ask him to do so.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Yalahari Quest",
			startStorageId = 11002,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Mission 1: Love is in the air",
					storageId = 11002,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 9,
					states = {
						[1] = "Ariel asked you to hand over a party invitation to Madame Malkin.",
						[2] = "Madame refused Ariel's request to go out with him. Tell him this bad news.",
						[3] = "Perhaps Ariel's friend, Old Postman, knows a way to influence Madame Malkin.",
						[4] = "Old Postman had a disgraceful idea to steal an elixir of love. He told you to fill this vial he gave you. You can probably find supplies of love elixir at Alchemists' quarters, north of MirkoTown.",
						[5] = "Success! You filled the vial with an elixir. Go back to the postman and ask him for further directions.",
						[6] = "Old Postman mentioned that in order for the elixir to properly work, you need to dilute Ariel's string of hair in it. After you do this, bring the elixir to Madame Malkin.",
						[8] = "Turns out that the “wine” worked as intended. Tell Ariel about it.",
						[9] = "Ariel rejoices to know about Madame's feelings. He also revealed the secret Yalaharian greeting to you: Aloha. You can visit Gertrdue or Konmuld now.",
					},
				},
				[2] = {
					name = "Mission 2: A morbid Liquor",
					storageId = 11044,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Find an immensely strong vodka in the lizard headquarters, and bring it to Gertruda.",
						[2] = "In exchange for your help with finding the beverage, Gertruda is willing to help you with preparing concoctions and special rodenticides.",
						[3] = "After treating Konmuld with vodka, he agreed to talk with you.",
					},
				},
				[3] = {
					name = "Mission 3: Prelude to Thaumaturgy",
					storageId = 11047,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 5,
					states = {
						[1] = "Konmuld asked you to bring him a virgin's soul. You can ask Grave Digger for help with your mission.",
						[2] = "Grave Digger said that there are no remaining virgins left, however, you can dig up a virgin's soul from a grave.",
						[3] = "You managed to get a virgin's soul. Now go see Konmuld.",
						[4] = "Konmuld offered you to choose one of the Yalahari set pieces to keep for yourself.",
						[5] = "In his gratitude, Konmuld gave you one of his old Yalahari set pieces.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "The First Steps",
			startStorageId = 11019,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Research",
					storageId = 11019,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 12,
					states = {
						[1] = "Find Commissioner Fisher and ask for a mission.",
						[2] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 0/10.",
						[3] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 1/10.",
						[4] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 2/10.",
						[5] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 3/10.",
						[6] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 4/10.",
						[7] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 5/10.",
						[8] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 6/10.",
						[9] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 7/10.",
						[10] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 8/10.",
						[11] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 9/10.",
						[12] = "Visit main dealers in MirkoTown and ask if they need any help. Then report it back to Commissioner Fisher. Dealers met: 10/10.",
					},
				},
				[2] = {
					name = "Wood Delivery",
					storageId = 11030,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 6,
					states = {
						[1] = "Go to Knurowo's port and find out what happened to the wood delivery.",
						[2] = "Woody is sure that the wood was shipped on a caravan leaving Knurowo. He asked you to investigate this.",
						[3] = "Tell Ryba that Waski and his mafia stole all of the wood delivery.",
						[4] = "Commissioner Fisher ordered you to recover the stolen wood, but he also warned you about the Waski's mafia.",
						[5] = "Waski gave up, and he is going to let Officer Ryba take the wood back. Report back to Ryba.",
						[6] = "Your merits earned you a special reward. Officer Ryba sent you to Trollsky, where you can receive your reward.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "To Carry the Pigs",
			startStorageId = 11034,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "To be like the Schwarzenegger",
					storageId = 11033,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Collect these items for me: 5 orc tooth, 5 carrion worm fangs, and 1 vampire teeth.",
						[2] = "Arni glanced at these teeth, and asked you to find someone who can make them into necklace.",
						[3] = "Madame Malkin gladly made this necklace for Arni.",
						[4] = "In exchange for the teeth necklace, Arni gave u his old armour and a ring.",
					},
				},
				[2] = {
					name = "Half turn Kick",
					storageId = 11035,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Cordell Walker is suspecting bandits of commissioning illegal transactions in their encampment.",
						[2] = "He was right. Now go to the Price Kebab and ask Shivganesh for translation.",
						[3] = "It wasn't hard at all for Shivganesh. Take the list and translation back to Cordell Walker.",
						[4] = "You have received MirkoTown guard hat for your help.",
					},
				},
				[3] = {
					name = "A Balanced Diet",
					storageId = 11037,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Collect 1 slimming carrot for fat Mirek.",
						[2] = "The carrot was dogshit, and u received chocolate slush in for your effort.",
					},
				},
				[4] = {
					name = "Kitz's Dominando",
					storageId = 11039,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					states = {
						[1] = "Arrange a special bow from elf adobe.",
						[2] = "You have received the item from Legolas. Go give it to Kitz.",
						[3] = "Turns out elvish bow sucks. Kitz now wishes to rook the elves. In return for your efforts you received his old bow.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Ocellatus Xddd",
			startStorageId = 11041,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Tickets",
					storageId = 11041,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 5,
					states = {
						[1] = "Recover the match tickets whose have been stolen from Ocellatus.",
						[2] = "You found the Tickets in a bandits tent.",
						[3] = "You gave tickets back to Ocellatus.",
						[4] = "Ocellatus asks you to bring him specific food. Ask Pewter for help.",
						[5] = "U brang food to Ocellatus. In his gratitude, he gave you outfit and let you sail his boat.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Demon Oak",
			startStorageId = 1013,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Demon Oak",
					storageId = 1013,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "You have made your way into the den of Demon Oak. Try to find someone who will tell you more about it.",
						[2] = "Oldrak gave you information regarding Demon Oak. He can bless an axe if you bring him one. The blessed axe should help you fight the Oak.",
						[3] = "You defeated the Demon Oak! Report to Oldrak.",
						[4] = "You reported to Oldrak about your victory. You have been rewarded for your efforts: Oldrak told you a secret about the way to the Elvish treasury.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Local Support",
			startStorageId = Storage.TrudnePoczatki.Rozeznanie,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Freaking Rats",
					storageId = Storage.PomocMiejscowym.PrzekleteSzczury,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Walmart wishes she knew how to repel rats. Find out where Gertruda lives. She should know how to craft a rat poison.",
						[2] = "Gertruda asked you to bring her one mouldy cheese.",
						[3] = "Cheese is now poisonous. Bring it to Walmart, so she can repel the rats.",
						[4] = "Walmart didn't have time to make use of the poisonous cheese, but she already gave you your reward: Carrot cake and a minor gift.",
					},
				},
				[2] = {
					name = "Cheap Recycling",
					storageId = Storage.PomocMiejscowym.TaniRecykling,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Malkin asked you to bring her 1 piece of cloth of every color.",
						[2] = "Madame Malkin is grateful for your effort, and since now you can exchange mystic turbans, red robe, and green tunic for corresponding pieces of cloth.",
					},
				},
				[3] = {
					name = "Broken Orb",
					storageId = Storage.PomocMiejscowym.ZniszczonaKula,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Gypsy needs a new Crystal ball. Bring it to him, and he will reward you abundantly.",
						[2] = "The crystal ball wasn't perfect, but Gypsy is fine with it. Since now he will also let you exchange red gem to ring of healing.",
					},
				},
				[4] = {
					name = "Biodegradable",
					storageId = Storage.Biodegradowalny.Questline,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Old postman asked you to find a package. You know that this cargo was supposed to arrive by water from the west.",
						[2] = "You found the package for Old Postman. Return to him and give it to him.",
						[3] = "You received a reward from Old Postman in exchange for helping locate the overdue shipment. He mentioned that you can also deliver Zanet's Box to Old Anon.",
						[4] = "You took the box from Old Postman, which you should deliver to Old Anon.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "The Silence of the Lambs",
			startStorageId = 11065,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "The test of Strength",
					storageId = 11065,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Lecter asked you for 5 vampire teeth.",
						[2] = "In exchange for your help, Lecter bestowed you with his old soul-extraction tool.",
					},
				},
				[2] = {
					name = "Fashionista clothes",
					storageId = 11066,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Lecter asked you to bring him 20 leathers of every kind.",
						[2] = "For your help you have been taught how to skin human carcass.",
					},
				},
				[3] = {
					name = "Lecter's recipe",
					storageId = 11073,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Lecter wants you to hoard 15 human hearts and 20 human livers. He needs them for his cannibals party.",
						[2] = "In exchange for this favor you have been introduced to the cannibal club. You also received their outfits.",
					},
				},
				[4] = {
					name = "Hearts collected",
					storageId = 11074,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 15,
					description = "Hearts collected",
				},
				[5] = {
					name = "Livers collected",
					storageId = 11075,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 20,
					description = "Livers collected Status",
				},
			},
		},
		[NextQuestId()] = {
			name = "Unwanted Guests",
			startStorageId = 11076,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Damned Barbarians",
					storageId = 11076,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "Bring Brutetamers Staff and Fur Boots to Dziadek Mroz.",
				},
			},
		},
		[NextQuestId()] = {
			name = "The Inquisition",
			startStorageId = 12160,
			startStorageValue = 2,
			missions = {
				[1] = {
					name = "Mission 1: Interrogation",
					storageId = 12161,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 7,
					description = "Your mission is to investigate the 5 guards regarding the Heretic behavior. Tim, Kulag, Grof, Miles and Walter are their names. If you do well you see a holy sprite on you.",
					states = {
						[1] = "You investigated 1 of 5 guards.",
						[2] = "You investigated 2 of 5 guards.",
						[3] = "You investigated 3 of 5 guards.",
						[4] = "You investigated 4 of 5 guards.",
						[5] = "You investigated 5 of 5 guards. Get back to Sybir and report your mission to Henricus.",
						[6] = "You investigated all guards.",
					},
				},
				[2] = {
					name = "Mission 2: Eclipse",
					storageId = 12162,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					description = "Henricus tells you to get The Witches' Grimoire, he sends you to Mirko Town where you can find to the witches' swamps. Use the vial of holy water that he gives you on the big cauldron and open the chest hidden in some witch hut, then bring the witches' grimoire to Henricus.",
					states = {
						[1] = "Find The Witches' Grimoire and bring it to Henricus.",
						[2] = "You already brought The Witches' Grimoire to Henricus.",
					},
				},
				[3] = {
					name = "Mission 3: Vampire Hunt",
					storageId = 12163,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 6,
					description = "Henricus wants you to find the Dwarfish Vampire Hunter, Storkus, located deep in dwarven mines. It's a good idea to bring your 20 Vampire Dusts with you to save some time.",
					states = {
						[1] = "Go back to Storkus and ask for a mission.",
						[2] = "Now Storkus wants you to kill a vampire lord, The Count. The Count is located deep under the forgotten cemetery near the hunter camp. To summon The Count, you must use the coffin in the center of the room. Kill him and bring The Ring of the Count to Storkus.",
						[3] = "Kill The Count and bring his ring to Storkus, and then ask for a mission.",
						[4] = "Return to Henricus and tell him that you've finished your job here.",
						[5] = "Get back to Sybir and report your mission to Henricus.",
					},
				},
				[4] = {
					name = "Mission 4: The Haunted Ruin",
					storageId = 12164,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					description = "Henricus will give you a Special Flask (vial of holy water). You can find some abandoned pirate ruins near hero village in the jungle. Use this vial of holy water on some spot in the haunted ruin to drive out the evil being.",
					states = {
						[1] = "Kill the Pirate Ghost and get back to Sybir and report your mission to Henricus.",
						[2] = "You already cleaned the abandoned and haunted place, ask Henricus for a new mission.",
					},
				},
				[5] = {
					name = "Mission 5: Essential Gathering",
					storageId = 12165,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					description = "Henricus wants 20 Demonic Essences as proof of your accomplishments.",
					states = {
						[1] = "Now ask Henricus for an outfit to get the Demon Hunter Outfit.",
						[2] = "You got the Demon Hunter Outfit! Ask Henricus for a mission to unlock more addons.",
					},
				},
				[6] = {
					name = "Mission 6: The Demon Ungreez",
					storageId = 12166,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 3,
					description = "Henricus wants you to kill a demon called Ungreez. Head to the desert demon lair and go down a few levels.",
					states = {
						[1] = "You killed Ungreez, report your mission to Henricus.",
						[2] = "You got the first addon of Demon Hunter Outfit! Ask Henricus for a mission to unlock more addons.",
					},
				},
				[7] = {
					name = "Mission 7: The Shadow Nexus",
					storageId = 12167,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 5,
					description = "Your mission is to go to the Demon Forge and slay seven of The Ruthless Seven Minions. The Demon Forge is located in the Sybir, somewhere in hidden cultist ruins.",
					states = {
						[1] = "You destroyed the shadow nexus! Get back to Henricus and report your mission.",
						[2] = "Now ask Henricus for an outfit. He will give you the 2nd addon of the Demon Hunter Outfits.",
						[3] = "You got the second addon of Demon Hunter Outfit! Go now to the reward room and choose one wisely!",
						[4] = "You have completed The Inquisition Quest!",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Bigfoot's Burden",
			startStorageId = 900,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Reputation points",
					storageId = 921,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 1000,
					description = "Current reputation points",
				},
				[2] = {
					name = "Daily Minor: Crystal Keeper",
					storageId = 932,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 5,
					description = "Daily Minor: Crystal Keeper Status",
				},
				[3] = {
					name = "Daily Minor: Raiders of the lost Spark",
					storageId = 934,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 7,
					description = "Daily Minor: Raiders of the lost Spark Status",
				},
				[4] = {
					name = "Daily Minor Plus: Exterminators",
					storageId = 937,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 10,
					description = "Daily Minor Plus: Exterminators Status",
				},
				[5] = {
					name = "Daily Minor Plus: Mushroom Digger",
					storageId = 940,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 3,
					description = "Daily Minor Plus: Mushroom Digger Status",
				},
				[6] = {
					name = "Daily Major Advanced: Spores",
					storageId = 948,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					description = "Gather spores in the correct order. Your spore gathering list will display the next color you have to look for.",
				},
				[7] = {
					name = "Daily Major Advanced: Yet Another Grinding",
					storageId = 952,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 1,
					description = "Gather a grindstone from the lava area and report back.",
				},
				[8] = {
					name = "Daily Major: Matchmaker",
					storageId = 943,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					description = "You have to enter the crystal caves and find a crystal that is fitting the crystal you got from the gnomes. Use the crystal on one of the bigger red crystal in the caves to bond them.",
				},
				[9] = {
					name = "Daily Major: The Tinker's Bell",
					storageId = 946,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					description = "Daily Major: The Tinker's Bell Status",
				},
			},
		},
		[NextQuestId()] = {
			name = "The Ape City",
			startStorageId = 11101,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Hairycles Missions",
					storageId = 11102,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 18,
					states = {
						[1] = "Find whisper moss in the dworc settlement and bring it back to Hairycles.",
						[2] = "You have completed the first mission. Hairycles was happy about the whisper moss you gave to him. He might have another mission for you.",
						[3] = "Hairycles asked you to bring him cough syrup from a human settlement. A healer might know more about this medicine.",
						[4] = "You have completed the second mission. Hairycles was happy about the cough syrup you gave to him. He might have another mission for you.",
						[5] = "Hairycles asked you to bring him a magical scroll from the lizard settlement.",
						[6] = "You have completed the third mission. Hairycles appreciated that you brought the scroll to him and will try to read it. Maybe he has another mission for you later.",
						[7] = "Since Hairycles was not able to read the scroll you brought him, he asked you to visit a tomb northwest from Hurghada. Proceed in this tomb until you find an obelisk between red stones and read it.",
						[8] = "You have completed the fourth mission. Hairycles read your mind and can now translate the lizard scroll. He might have another mission for you.",
						[9] = "Hairycles wants to create a life charm for the ape people. He needs a hydra egg since it has strong regenerating powers.",
						[10] = "You have completed the fifth mission. Hairycles attempts to create a might charm for the protection of the ape people. He might have another mission for you later.",
						[11] = "Hairycles need a witches' cap mushroom which is supposed to grow on swamp inhabited by Beholders.",
						[12] = "You have completed the sixth mission. You brought the witches' cap mushroom back to Hairycles. He might have another mission for you.",
						[13] = "Hairycles read that the Lizards are planning to summon the Demon Lizards to help regain their former temple. Perhaps the premature lighting of their firecamp will thwart their plans.",
						[14] = "You have completed the seventh mission. You found a way to prevent the Lizards from opening the hellish gates. Hairycles might have another mission for you.",
						[15] = "The apes now need a symbol of their faith. Find a hair of the giant, holy ape and bring it back. It may be located in caves inhabited by Behemoths.",
						[16] = "You completed the eighth mission. Hairycles gladly accepted the hair of the ape god which you brought him. He told you to have one final mission for you.",
						[17] = "Go into the deepest catacombs under Banuta and destroy the monument of the snake god with the hammer that Hairycles gave to you.",
						[18] = "You successfully destroyed the monument of the snake god. As reward, you can buy sacred statues from Hairycles. If you haven't done so yet, you should also ask him for a shaman outfit.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Top Chef",
			startStorageId = Storage.TopChef.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Top Chef",
					storageId = Storage.TopChef.Questline,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 16,
					description = "TOP_CHEF_MISSION_DESCRIPTION",
				},
			},
		},
		[NextQuestId()] = {
			name = "The Dream Courts",
			startStorageId = 12200,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "The Dream Courts",
					storageId = 12200,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 5,
					description = "Find and talk to Vanys in order to help him. He stays in Summer Court in the huge forest located far south from Mirko Town.",
					states = {
						[1] = "Vanys gave you a dream talisman that you'll need to empower eight ward stones located around the world. Ward stone locations you were told about are: mountains of Pirate Island, bonebast coast in the desert, water elemental cave beneath Kongo, depths of Seacrest Serpent lair, west coast of Sybir and Barbarian camp, Nightmare Island, Buried Cathedral beneath Karaiby.",
						[2] = "Vanys let you enter the dream labyrinth. Find a way to enter the Nightmare Beast's lair and defeat him. Elven Parchment from Vanys chest may help you.",
						[3] = "You have defeated The Nightmare Beast. Talk about this to Vanys.",
						[4] = "Vanys gifted you with a traditional dream warrior outfit.",
					},
				},
				[2] = {
					name = "Helping of Stricken Soul",
					storageId = 12232,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					description = "Restore connection and open this nexus to access the buried cathedral. You need to find a way to pass the entrance in the cellar.",
					states = {
						[1] = "You successfully passed the cellar entrance. Find a way to restore the portal to the buried cathedral.",
						[2] = "You restored a portal and successfully entered the buried cathedral. Try to find and defeat the Faceless Bane. You'll need to gain some knowledge in order to enter her nest. Maybe there are some documents around...",
						[3] = "You successfully defeated the Faceless Bane.",
					},
				},
				[3] = {
					name = "Empowered Wardstones",
					storageId = 12209,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 8,
					description = "Empowered Wardstones",
				},
				[4] = {
					name = "Readed documents",
					storageId = 12214,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 4,
					description = "Readed documents",
				},
			},
		},
		[NextQuestId()] = {
			name = "Liquid Black",
			startStorageId = 24001,
			startStorageValue = 2,
			missions = {
				[1] = {
					name = "Visitor",
					storageId = 24001,
					missionId = NextMissionId(),
					startValue = 2,
					endValue = 5,
					states = {
						[2] = "You have found notes and coordinates. Try to find out what they are for.",
						[3] = "You got teleported to Mezamir by a strange teleporter. Ask him about this machine.",
						[4] = "Mezamir let you dive into the place he tried to discover years ago. Find a large staircase heading underwater on Pirate Island and find out what's below.",
						[5] = "You have found a shortcut to the deeplings' underwater base.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "IKEA for the BOLD",
			startStorageId = 11077,
			startStorageValue = 0,
			missions = {
				[1] = {
					name = "The Stocktaking",
					storageId = 11077,
					missionId = NextMissionId(),
					startValue = 0,
					endValue = 6,
					states = {
						[0] = "Commissioner Fisher has mentioned that Komor needs help.",
						[1] = "Komor needs help dealing with the disappearing furniture from his warehouse.",
						[2] = "Komor let you ask Gypsy if he knows anything about the theft of the furniture.",
						[3] = "Try to find the thief; he's possibly hiding in the sewers.",
						[4] = "You found the thief, but he managed to get away. Try to look around his hideout.",
						[5] = "You found a list of stolen items; the thief has apparently stolen more than just furniture. Go to Komor and give him the list.",
						[6] = "You helped Komor and got rewarded for that. You have started the new mission 'Needle in a Haystack'.",
					},
				},
				[2] = {
					name = "Needle in a Haystack",
					storageId = 11077,
					missionId = NextMissionId(),
					startValue = 6,
					endValue = 14,
					states = {
						[6] = "You helped Komor find his stolen furniture. Get your reward from the floor above if you haven't already. Visit Komor again to find out what he found on the list.",
						[7] = "Komor asked you to consult Commissioner Fisher about the thief.",
						[8] = "Fish asked you to track down the thief. Perhaps someone from nearby saw where he ran away?",
						[9] = "Find the bandit camp and see if they have anything to do with it.",
						[10] = "Ask the bandit leader about the furniture thief.",
						[11] = "Everything indicates that the thief is trying to smuggle items and hide in the steppes. The bandit leader suggested where you should go now.",
						[12] = "You have defeated the Lumberjack Domino, look around his hiding place.",
						[13] = "From now on, you can use his boat. Report to Commissioner Fisher.",
						[14] = "You finished the plot of Lumberjack Domino, from now on you can sail his boat from the bandit camp to the south of the steppes.",
					},
				},
			},
		},
		[NextQuestId()] = {
			name = "Settled down Fishmonger",
			startStorageId = Storage.UstatkowanyFanatyk.Questline,
			startStorageValue = 1,
			missions = {
				[1] = {
					name = "Stagnation",
					storageId = Storage.UstatkowanyFanatyk.Mission01,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Anon's father is waiting for his order.",
						[2] = "You helped Anon's father recover his long-awaited package. Ask him for new mission now.",
					},
				},
				[2] = {
					name = "Milksop",
					storageId = Storage.UstatkowanyFanatyk.Mission02,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 2,
					states = {
						[1] = "Anon's father needs help finding some old junk he carried with him for fishing. Search all boats, piers, and swamps around Mirko Town for any found items.",
						[2] = "You helped Anon's father collect his lost tools.",
					},
				},
				[3] = {
					name = "Stew for Trouble",
					storageId = Storage.UstatkowanyFanatyk.Mission03,
					missionId = NextMissionId(),
					startValue = 1,
					endValue = 4,
					states = {
						[1] = "Anon's father received his table in a deplorable state, ask how you can improve his mood.",
						[2] = "Anon's father reacted strongly to the fact that someone destroyed his little table. Bring some of his favorite dishes, and he might calm down. Anon's father mentioned that he loves Rotworm Stew.",
						[3] = "You helped Anon's father with all the troubles. Now, go to his son for your reward.",
						[4] = "You have received a reward from the Fisherman Son. You gained the ability to purchase Shimmer Swimmer.",
					},
				},
			},
		},
	}
end
